class AppStrings {
  static const String appName = 'PixelRevive';

  static const Map<String, Map<String, String>> localizedValues = {
    'en': {
      'tagline': 'Professional AI Photo Enhancer',
      'subTagline': 'Restore, Enhance & Unblur Your Old Memories Instantly',

      // Navigation
      'tabAiLab': 'AI Lab',
      'tabSaved': 'Saved',
      'tabSettings': 'Settings',

      // General
      'chooseFeature': 'Select AI Feature',
      'onDevice': 'Instant on-device processing. No internet required.',
      'gallery': 'Gallery',
      'camera': 'Camera',
      'selectPhoto': 'Select a photo to begin',
      'importBlurry': 'Import a blurry or old photo to experience the AI filters',
      'changePhoto': 'Change Photo',
      'aiEditor': 'AI Editor',
      'aiStudio': 'AI Photo Studio',
      'enhance': 'Enhance',
      'compare': 'Compare',
      'save': 'Save',
      'share': 'Share',
      'cancel': 'Cancel',
      'closeBtn': 'Close',
      'confirm': 'Confirm',
      'processingLabel': 'Processing...',
      'next': 'Next',
      'skip': 'Skip',
      'getStarted': 'Get Started',

      // Language screen
      'chooseLanguage': 'Choose Language',
      'searchLanguage': 'Search language...',
      'noLanguagesFound': 'No languages found',

      // Settings
      'settingsTitle': 'Settings',
      'appLanguage': 'App Language',
      'shareFriends': 'Share with Friends',
      'shareFriendsSub': 'Spread the word about PixelRevive',
      'rateUs': 'Rate Us',
      'rateUsSub': 'Support us on the Play Store',
      'terms': 'Terms of Service',
      'termsSub': 'Read our legal guidelines',
      'privacy': 'Privacy Policy',
      'privacySub': 'Read our data handling rules',
      'appNameFull': 'PixelRevive AI Photo Studio',

      // Onboarding
      'onboardingTitle1': 'AI Old Photo Restore',
      'onboardingSub1': 'Instantly restore faded colors, remove aging sepia casts, and bring back deep contrasts to family archives.',
      'onboardingTitle2': 'Ultra HD 4K Upscale',
      'onboardingSub2': 'Enlarge your low-resolution, pixelated, or blurry images up to 4x with sharp edges and clear details.',
      'onboardingTitle3': 'DSLR Background Blur',
      'onboardingSub3': 'Simulate expensive camera bokeh. Focus on your subjects and smoothly blur complex background distractions.',

      // AI Lab hero
      'cloudBadge': 'SECURE CLOUD AI PROCESSING ⚡',
      'onDeviceBadge': 'ON-DEVICE AI PROCESSING',
      'cloudHeadline': 'Ultra HD Facial Reconstruction\nPowered by Cloud GPUs',
      'cloudDesc': 'Running state-of-the-art models on high-speed servers for mind-blowing crystalline details.',
      'onDeviceHeroDesc': 'Breathe new life into pixelated, blurry, or black & white photos locally on your phone without uploading them anywhere.',
      'batchTitle': 'Batch AI Enhance',
      'batchSub': 'Process multiple images in parallel instantly',
      'showcaseTitle': 'Interactive Showcase',
      'showcase1Title': 'Family Archivist',
      'showcase1Sub': 'Colorize and clear scratches',
      'showcase1Desc': 'Brings aged, faded sepia portraits back to life with vibrant, realistic color balance and crisp contrasts.',
      'showcase2Title': 'Crystalline Face',
      'showcase2Sub': 'HD upscaling & edge sharp',
      'showcase2Desc': 'Increases blurry or pixelated details using advanced sub-pixel scaling and sharpening.',
      'showcase3Title': 'Bokeh Portrait',
      'showcase3Sub': 'DSLR vignette blur depth',
      'showcase3Desc': 'Keeps facial subjects in perfect focus while smoothly feathering and blurring cluttered backgrounds.',

      // Editor
      'cropRotate': 'Crop & Rotate',
      'noImageSelected': 'No image selected',
      'enhanceStrength': 'Enhance Strength',
      'faceStrength': 'Face Enhance Strength',
      'skinSmoothness': 'Skin Smoothness',
      'bokehDepth': 'Background Bokeh Depth',
      'upscaleSize': 'Upscale Size',
      'fastHd': 'Fast HD',
      'ultraHd': 'Ultra HD',
      'upscaleNote': '4x creates larger files and may take longer, especially on-device.',

      // Saved Images
      'myCreations': 'My Creations',
      'noCreationsTitle': 'No Saved Creations',
      'noCreationsSub': 'Your enhanced masterpieces will appear here immediately after you save them to your gallery.',
      'enhancedPhoto': 'Enhanced Photo',
      'nSelected': 'Selected',
      'deleteSelected': 'Delete Selected',
      'deleteAllHistory': 'Delete All History',
      'deleteAllTitle': 'Delete All Saved Images?',
      'deleteAllSub': 'This will permanently delete all your saved AI enhanced creations from both the history and your device storage. This action cannot be undone.',
      'deleteAll': 'Delete All',
      'deletedSelectedSnack': 'Selected photos deleted successfully.',
      'allDeletedSnack': 'All creations deleted from disk.',
      'unknownDate': 'Unknown Date',

      // Result
      'resultTitle': 'Before & After Swipe',
      'freeExports': 'Free exports remaining:',
      'watermarkNotice': 'Free saves include a small watermark on the corner.',
      'successTitle': 'Masterpiece Saved!',
      'successSub': 'Your enhanced photo has been saved to your phone gallery and kept in PixelRevive history.',
      'excellent': 'Excellent',
      'limitReachedTitle': 'Free Limit Reached',
      'limitReachedSub': 'You have utilized all free exports for today. Upgrade to Premium for unlimited exports without watermark and full HD resolution.',
      'later': 'Later',
      'goPremium': 'Go Premium',
      'imageMissing': 'Image bytes missing. Please re-run process.',
      'openGallery': 'Open Gallery',
      'saveFailedSnack': 'Failed to save to phone gallery. Please allow Photos/Gallery access.',

      // Premium
      'unlockPremium': 'Unlock Premium Now',
      'premiumActive': '✓ Premium Active',
      'freeSaves': 'Free saves remaining today:',
      'proBenefitTitle': 'PRO Features Included',
      'tapToCompare': 'TAP TO COMPARE 👆',
      'benefit1': 'Ultra HD exports with no compression',
      'benefit2': 'No watermark on your finished photos',
      'benefit3': 'Unlimited daily photo enhancements',
      'benefit4': 'High-priority processing (Coming soon)',
      'benefit5': 'Batch processing for multiple photos',
      'premiumTitle': 'Premium Upgrade',
      'devSettings': 'Developer API Settings',
      'enableCloud': 'Enable Cloud AI (Fal.ai)',
      'apiDesc': 'Insert your private Fal.ai API token to run state-of-the-art AI models (GFPGAN, Real-ESRGAN, CodeFormer) on high-speed cloud GPUs.',
      'apiHint': 'Paste Fal.ai Token here...',
      'selectPlan': 'Select a Plan',
      'weekly': 'Weekly',
      'yearly': 'Yearly Premium',
      'lifetime': 'Lifetime Ultra',
      'bestValue': 'BEST VALUE',
      'forever': 'FOREVER',
      'payOnce': 'Pay once, use forever',
      'autoRenews': 'Auto-renews easily. Cancel anytime.',
      'localUnlockSnack': 'Success! You are now a PRO member.',
      'billingNotice': 'Google Play Billing is wired and ready. After your Play Developer account is set up and products (premium_weekly / premium_yearly / premium_lifetime) are created, real purchases activate with no code change.',

      // Batch
      'batchStudio': 'Batch AI Studio',
      'clearBatch': 'Clear Batch',
      'batchEmptyTitle': 'Batch Photo Enhance',
      'batchEmptySub': 'Select multiple photos from your library to restore, upscale, or colorize them all in one single high-speed queue!',
      'selectBatchPhotos': 'Select Batch Photos',
      'selectBatchAction': 'Select AI Batch Action:',
      'processNImages': 'Process Images',
      'batchDoneMsg': 'All photos processed successfully! You can now save them to your device gallery in one tap.',
      'saveAllGallery': 'Save All to Gallery',
      'batchSavedSnack': '🎉 All batch photos saved successfully to your gallery!',
      'processingQueue': 'Processing queue...',
      'batchKeepOpen': 'Processing your queue. Cloud is used for Premium when available; otherwise local fallback is used. Please keep the app open.',
      'premiumFeature': 'Premium Feature',
      'premiumBatchSub': 'Batch AI Processing is a PRO exclusive feature. Upgrade to Premium to process multiple photos in one queue, save all results, and use cloud enhancement when available.',
      'maybeLater': 'Maybe Later',

      // Processing dialog
      'aiProcessing': 'AI Processing...',
      'phrase1': 'Scanning image pixels...',
      'phrase2': 'Decompressing resolution...',
      'phrase3': 'Detecting facial structures...',
      'phrase4': 'Smoothing skin gradients...',
      'phrase5': 'Reconstructing high-frequency details...',
      'phrase6': 'Applying split-toning highlights...',
      'phrase7': 'Saving secure local export...',

      // Feature Descriptions
      'desc_auto': 'One-Tap Auto Enhance automatically optimizes brightness, balances contrast, restores saturation, and sharpens soft details for a balanced photo.',
      'desc_upscale': 'HD Upscale lets you choose 2x or 4x enlargement. Premium users can use secure cloud upscaling when available; local fallback uses bicubic resizing plus sharpening.',
      'desc_face': 'Face Enhance optimizes portraits. It applies a smart local smoothing pass to reduce skin blemishes, followed by a local high-contrast details pass.',
      'desc_denoise': 'Denoise utilizes a bilateral noise-reduction filter. It sweeps away sensor grain and low-light artifacts while preserving structural edges.',
      'desc_unblur': 'Unblur deploys a high-pass unsharp masking algorithm, pulling back details in out-of-focus or motion-blurred shots.',
      'desc_colorize': 'Colorize B&W adds a warm color treatment to monochrome photos locally. Dedicated historical AI colorization can be added later through the backend model pipeline.',
      'desc_restore': 'Old Photo Restore improves faded, yellowed, or sepia photos by balancing color, contrast, noise, and sharpness. Cloud mode can enhance faces/details when available.',
      'desc_cartoon': 'Cartoon Effect processes the image with color quantization and edge tracing, turning normal photos into hand-drawn digital cel-shaded pop art.',
      'desc_bg': 'Background Blur simulates premium lens bokeh. It detects faces with on-device ML and keeps them sharp while smoothly softening the surrounding background.',
      'desc_bg_cleanup': 'BG Cleanup uses cloud remove-background when available. If cloud is unavailable, the local fallback reduces background distractions with center-focus cleanup.',

      // Feature Card Titles & Subtitles
      'feat_auto_title': 'Auto Enhance',
      'feat_auto_sub': 'Fix colors, contrast & sharpness',
      'feat_upscale_title': 'HD Upscale',
      'feat_upscale_sub': '2x / 4x enlarge without blur',
      'feat_face_title': 'Face Enhance',
      'feat_face_sub': 'Sharpen & smooth faces',
      'feat_denoise_title': 'Denoise',
      'feat_denoise_sub': 'Remove grain & noise',
      'feat_unblur_title': 'Unblur',
      'feat_unblur_sub': 'Reduce motion & soft blur',
      'feat_colorize_title': 'Colorize B&W',
      'feat_colorize_sub': 'Add warm color to old photos',
      'feat_restore_title': 'Old Photo Restore',
      'feat_restore_sub': 'Fix faded, sepia & scratches',
      'feat_cartoon_title': 'Cartoon Effect',
      'feat_cartoon_sub': 'Artistic edge & color pop',
      'feat_bg_title': 'Background Blur',
      'feat_bg_sub': 'Blur background, keep face sharp',
      'feat_bg_cleanup_title': 'BG Cleanup',
      'feat_bg_cleanup_sub': 'Remove background distractions',
    },
    'es': {
      'tagline': 'Mejorador de Fotos AI Profesional',
      'subTagline': 'Restaure, mejore y aclare sus viejos recuerdos al instante',

      'tabAiLab': 'Laboratorio IA',
      'tabSaved': 'Guardados',
      'tabSettings': 'Ajustes',

      'chooseFeature': 'Seleccionar función de IA',
      'onDevice': 'Procesamiento instantáneo en el dispositivo. Sin internet.',
      'gallery': 'Galería',
      'camera': 'Cámara',
      'selectPhoto': 'Seleccione una foto para comenzar',
      'importBlurry': 'Importe una foto borrosa o vieja para experimentar la IA',
      'changePhoto': 'Cambiar Foto',
      'aiEditor': 'Editor de IA',
      'aiStudio': 'Estudio de Fotos IA',
      'enhance': 'Mejorar',
      'compare': 'Comparar',
      'save': 'Guardar',
      'share': 'Compartir',
      'cancel': 'Cancelar',
      'closeBtn': 'Cerrar',
      'confirm': 'Confirmar',
      'processingLabel': 'Procesando...',
      'next': 'Siguiente',
      'skip': 'Omitir',
      'getStarted': 'Comenzar',

      'chooseLanguage': 'Elegir Idioma',
      'searchLanguage': 'Buscar idioma...',
      'noLanguagesFound': 'No se encontraron idiomas',

      'settingsTitle': 'Ajustes',
      'appLanguage': 'Idioma de la App',
      'shareFriends': 'Compartir con Amigos',
      'shareFriendsSub': 'Difunde PixelRevive',
      'rateUs': 'Califícanos',
      'rateUsSub': 'Apóyanos en Play Store',
      'terms': 'Términos de Servicio',
      'termsSub': 'Lee nuestras normas legales',
      'privacy': 'Política de Privacidad',
      'privacySub': 'Lee nuestras reglas de datos',
      'appNameFull': 'PixelRevive Estudio de Fotos IA',

      'onboardingTitle1': 'Restauración de fotos antiguas por IA',
      'onboardingSub1': 'Restaura instantáneamente colores desvaídos, elimina tonos sepia y devuelve contrastes profundos.',
      'onboardingTitle2': 'Escalado Ultra HD 4K',
      'onboardingSub2': 'Amplía tus imágenes borrosas o pixeladas hasta 4 veces con bordes definidos y detalles claros.',
      'onboardingTitle3': 'Desenfoque de fondo DSLR',
      'onboardingSub3': 'Simula el bokeh de cámaras profesionales. Enfoca tus sujetos y desenfoca fondos complejos.',

      'cloudBadge': 'PROCESAMIENTO IA EN NUBE SEGURO ⚡',
      'onDeviceBadge': 'PROCESAMIENTO IA EN DISPOSITIVO',
      'cloudHeadline': 'Reconstrucción Facial Ultra HD\nPotenciada por GPUs en la Nube',
      'cloudDesc': 'Ejecutando modelos de vanguardia en servidores de alta velocidad para detalles cristalinos impresionantes.',
      'onDeviceHeroDesc': 'Da nueva vida a fotos pixeladas, borrosas o en blanco y negro localmente en tu teléfono sin subirlas a ningún lado.',
      'batchTitle': 'Mejora IA por Lotes',
      'batchSub': 'Procesa múltiples imágenes en paralelo al instante',
      'showcaseTitle': 'Galería Interactiva',
      'showcase1Title': 'Archivero Familiar',
      'showcase1Sub': 'Colorear y limpiar rasguños',
      'showcase1Desc': 'Devuelve a la vida retratos sepia desvaídos con colores vibrantes y realistas y contrastes nítidos.',
      'showcase2Title': 'Rostro Cristalino',
      'showcase2Sub': 'Escalado HD y bordes nítidos',
      'showcase2Desc': 'Aumenta los detalles borrosos o pixelados usando escalado de subpíxel avanzado y nitidez.',
      'showcase3Title': 'Retrato Bokeh',
      'showcase3Sub': 'Profundidad de desenfoque DSLR',
      'showcase3Desc': 'Mantiene los sujetos faciales en enfoque perfecto mientras difumina suavemente fondos desordenados.',

      'cropRotate': 'Recortar y Rotar',
      'noImageSelected': 'Ninguna imagen seleccionada',
      'enhanceStrength': 'Fuerza de Mejora',
      'faceStrength': 'Fuerza de Mejora de Rostro',
      'skinSmoothness': 'Suavidad de Piel',
      'bokehDepth': 'Profundidad de Bokeh',
      'upscaleSize': 'Tamaño de Escalado',
      'fastHd': 'HD Rápido',
      'ultraHd': 'Ultra HD',
      'upscaleNote': '4x crea archivos más grandes y puede tardar más, especialmente en el dispositivo.',

      'myCreations': 'Mis Creaciones',
      'noCreationsTitle': 'Sin Creaciones Guardadas',
      'noCreationsSub': 'Tus obras maestras mejoradas aparecerán aquí inmediatamente después de guardarlas en tu galería.',
      'enhancedPhoto': 'Foto Mejorada',
      'nSelected': 'Seleccionados',
      'deleteSelected': 'Eliminar Seleccionados',
      'deleteAllHistory': 'Eliminar Todo el Historial',
      'deleteAllTitle': '¿Eliminar Todas las Imágenes Guardadas?',
      'deleteAllSub': 'Esto eliminará permanentemente todas tus creaciones mejoradas con IA del historial y del almacenamiento del dispositivo. Esta acción no se puede deshacer.',
      'deleteAll': 'Eliminar Todo',
      'deletedSelectedSnack': 'Fotos seleccionadas eliminadas correctamente.',
      'allDeletedSnack': 'Todas las creaciones eliminadas del dispositivo.',
      'unknownDate': 'Fecha Desconocida',

      'resultTitle': 'Deslizar Antes y Después',
      'freeExports': 'Exportaciones gratuitas restantes:',
      'watermarkNotice': 'Los guardados gratuitos incluyen una marca de agua en la esquina.',
      'successTitle': '¡Obra Maestra Guardada!',
      'successSub': 'Su foto mejorada se ha guardado correctamente en la galería de su teléfono.',
      'excellent': 'Excelente',
      'limitReachedTitle': 'Límite de guardado alcanzado',
      'limitReachedSub': 'Has utilizado todas las exportaciones gratuitas para hoy. Actualiza a Premium para obtener descargas ilimitadas.',
      'later': 'Más tarde',
      'goPremium': 'Obtener Premium',
      'imageMissing': 'Faltan datos de imagen. Vuelve a procesar.',
      'openGallery': 'Abrir Galería',
      'saveFailedSnack': 'Error al guardar en la galería. Permite el acceso a Fotos/Galería.',

      'unlockPremium': 'Desbloquear Premium',
      'premiumActive': '✓ Premium Activo',
      'freeSaves': 'Guardados gratis restantes hoy:',
      'proBenefitTitle': 'Funciones PRO Incluidas',
      'tapToCompare': 'TOCA PARA COMPARAR 👆',
      'benefit1': 'Exportaciones Ultra HD sin compresión',
      'benefit2': 'Sin marca de agua en tus fotos finales',
      'benefit3': 'Mejoras de fotos diarias ilimitadas',
      'benefit4': 'Procesamiento de alta prioridad (Muy pronto)',
      'benefit5': 'Procesamiento por lotes para varias elementos (Muy pronto)',
      'premiumTitle': 'Mejora Premium',
      'devSettings': 'Configuración de API para Desarrolladores',
      'enableCloud': 'Habilitar Cloud AI (Fal.ai)',
      'apiDesc': 'Inserte su token de API de Fal.ai privado para ejecutar modelos de IA de última generación en servidores GPU en la nube.',
      'apiHint': 'Pegue el token de Fal.ai aquí...',
      'selectPlan': 'Seleccione un Plan',
      'weekly': 'Semanal',
      'yearly': 'Premium Anual',
      'lifetime': 'Ultra de por vida',
      'bestValue': 'BEST VALUE',
      'forever': 'PARA SIEMPRE',
      'payOnce': 'Paga una vez, usa para siempre',
      'autoRenews': 'Se renueva fácilmente. Cancela en cualquier momento.',
      'localUnlockSnack': '¡Éxito! Ahora eres miembro PRO.',
      'billingNotice': 'La facturación de Google Play está lista. Tras crear tu cuenta de desarrollador y los productos (premium_weekly / premium_yearly / premium_lifetime) en Play Console, las compras reales se activan sin cambios en el código.',

      'batchStudio': 'Estudio IA por Lotes',
      'clearBatch': 'Limpiar Lote',
      'batchEmptyTitle': 'Mejora de Fotos por Lotes',
      'batchEmptySub': '¡Selecciona varias fotos de tu biblioteca para restaurarlas, ampliarlas o colorearlas en una sola cola de alta velocidad!',
      'selectBatchPhotos': 'Seleccionar Fotos del Lote',
      'selectBatchAction': 'Seleccionar Acción IA:',
      'processNImages': 'Procesar Imágenes',
      'batchDoneMsg': '¡Todas las fotos procesadas correctamente! Ahora puedes guardarlas en tu galería con un toque.',
      'saveAllGallery': 'Guardar Todo en Galería',
      'batchSavedSnack': '🎉 ¡Todas las fotos del lote se guardaron correctamente en tu galería!',
      'processingQueue': 'Procesando cola...',
      'batchKeepOpen': 'Procesando tu cola. Se usa la nube para Premium cuando está disponible; de lo contrario, procesamiento local. Mantén la app abierta.',
      'premiumFeature': 'Función Premium',
      'premiumBatchSub': 'El Procesamiento IA por Lotes es exclusivo de PRO. Actualiza a Premium para procesar varias fotos en una cola, guardar todos los resultados y usar la mejora en la nube.',
      'maybeLater': 'Quizá Más Tarde',

      'aiProcessing': 'Procesando IA...',
      'phrase1': 'Escaneando píxeles de imagen...',
      'phrase2': 'Descomprimiendo resolución...',
      'phrase3': 'Detectando estructuras faciales...',
      'phrase4': 'Suavizando gradientes de piel...',
      'phrase5': 'Reconstruyendo detalles de alta frecuencia...',
      'phrase6': 'Aplicando iluminación de tonos divididos...',
      'phrase7': 'Guardando exportación local segura...',

      'desc_auto': 'Auto Enhance optimiza automáticamente el brillo, equilibra el contraste, restaura la saturación y enfoca los detalles suaves.',
      'desc_upscale': 'HD Upscale escala su foto usando interpolación bicúbica para duplicar (2x) o cuadruplicar (4x) la resolución.',
      'desc_face': 'Face Enhance suaviza la piel reduciendo imperfecciones y resalta los rasgos clave de la cara como ojos y labios.',
      'desc_denoise': 'Denoise elimina el grano digital y el ruido de las fotos oscuras manteniendo los bordes nítidos.',
      'desc_unblur': 'Unblur reduce el movimiento de la cámara y el desenfoque suave recuperando detalles finos en la imagen.',
      'desc_colorize': 'Colorize B&W agrega tonos de piel realistas y colores naturales a las fotos antiguas en blanco y negro.',
      'desc_restore': 'Old Photo Restore elimina el tono amarillento y sepia del envejecimiento y recupera el contraste original.',
      'desc_cartoon': 'Cartoon Effect transforma tus fotos en un estilo artístico de dibujo animado con bordes oscuros y colores planos.',
      'desc_bg': 'Background Blur desenfoca el fondo de tus retratos imitando el efecto bokeh de lentes profesionales.',
      'desc_bg_cleanup': 'BG Cleanup reemplaza las distracciones del fondo con un fondo de estudio limpio usando enmascaramiento inteligente centrado.',

      'feat_auto_title': 'Mejora Automática',
      'feat_auto_sub': 'Corrige colores, contraste y nitidez',
      'feat_upscale_title': 'Escalado HD',
      'feat_upscale_sub': 'Amplía 2x / 4x sin distorsión',
      'feat_face_title': 'Mejora de Rostro',
      'feat_face_sub': 'Suaviza y perfila facciones',
      'feat_denoise_title': 'Reducir Ruido',
      'feat_denoise_sub': 'Elimina grano y pixelación',
      'feat_unblur_title': 'Enfocar Foto',
      'feat_unblur_sub': 'Corrige el movimiento y borrosidad',
      'feat_colorize_title': 'Colorear B&N',
      'feat_colorize_sub': 'Añade color real a fotos viejas',
      'feat_restore_title': 'Restaurar Antigua',
      'feat_restore_sub': 'Quita manchas, sepia y dobleces',
      'feat_cartoon_title': 'Efecto Cartoon',
      'feat_cartoon_sub': 'Estilo cómic pop art de un toque',
      'feat_bg_title': 'Desenfocar Fondo',
      'feat_bg_sub': 'Efecto bokeh retrato profesional',
      'feat_bg_cleanup_title': 'Limpiar Fondo',
      'feat_bg_cleanup_sub': 'Elimina distracciones del fondo',
    },
    'fr': {
      'tagline': 'Améliorateur de Photos IA Professionnel',
      'subTagline': 'Restaurez, améliorez et défloutez vos vieux souvenirs instantanément',

      'tabAiLab': 'Labo IA',
      'tabSaved': 'Enregistrés',
      'tabSettings': 'Réglages',

      'chooseFeature': 'Sélectionner la fonction IA',
      'onDevice': 'Traitement instantané sur l\'appareil. Sans internet.',
      'gallery': 'Galerie',
      'camera': 'Appareil photo',
      'selectPhoto': 'Sélectionnez une photo pour commencer',
      'importBlurry': 'Importez une photo floue ou ancienne pour tester l\'IA',
      'changePhoto': 'Changer de photo',
      'aiEditor': 'Éditeur IA',
      'aiStudio': 'Studio Photo IA',
      'enhance': 'Améliorer',
      'compare': 'Comparer',
      'save': 'Enregistrer',
      'share': 'Partager',
      'cancel': 'Annuler',
      'closeBtn': 'Fermer',
      'confirm': 'Confirmer',
      'processingLabel': 'Traitement...',
      'next': 'Suivant',
      'skip': 'Passer',
      'getStarted': 'Commencer',

      'chooseLanguage': 'Choisir la Langue',
      'searchLanguage': 'Rechercher une langue...',
      'noLanguagesFound': 'Aucune langue trouvée',

      'settingsTitle': 'Réglages',
      'appLanguage': 'Langue de l\'App',
      'shareFriends': 'Partager avec des Amis',
      'shareFriendsSub': 'Parlez de PixelRevive',
      'rateUs': 'Nous Évaluer',
      'rateUsSub': 'Soutenez-nous sur le Play Store',
      'terms': 'Conditions d\'Utilisation',
      'termsSub': 'Lisez nos règles légales',
      'privacy': 'Politique de Confidentialité',
      'privacySub': 'Lisez nos règles de données',
      'appNameFull': 'PixelRevive Studio Photo IA',

      'onboardingTitle1': 'Restauration de Photos Anciennes par IA',
      'onboardingSub1': 'Restaurez instantanément les couleurs fanées, supprimez les teintes sépia et recréez des contrastes profonds.',
      'onboardingTitle2': 'Mise à l\'échelle Ultra HD 4K',
      'onboardingSub2': 'Agrandissez vos images floues ou pixelisées jusqu\'à 4x avec des contours nets.',
      'onboardingTitle3': 'Flou d\'arrière-plan DSLR',
      'onboardingSub3': 'Simulez le bokeh d\'un appareil photo professionnel. Restez focalisé sur vos sujets.',

      'cloudBadge': 'TRAITEMENT IA NUAGE SÉCURISÉ ⚡',
      'onDeviceBadge': 'TRAITEMENT IA SUR APPAREIL',
      'cloudHeadline': 'Reconstruction Faciale Ultra HD\nPropulsée par des GPUs Cloud',
      'cloudDesc': 'Exécution de modèles de pointe sur des serveurs haute vitesse pour des détails cristallins époustouflants.',
      'onDeviceHeroDesc': 'Donnez une nouvelle vie aux photos pixelisées, floues ou en noir et blanc localement sans les téléverser nulle part.',
      'batchTitle': 'Amélioration IA par Lots',
      'batchSub': 'Traitez plusieurs images en parallèle instantanément',
      'showcaseTitle': 'Galerie Interactive',
      'showcase1Title': 'Archiviste Familial',
      'showcase1Sub': 'Coloriser et effacer les rayures',
      'showcase1Desc': 'Redonne vie aux portraits sépia fanés avec des couleurs vibrantes et des contrastes nets.',
      'showcase2Title': 'Visage Cristallin',
      'showcase2Sub': 'Mise à l\'échelle HD et netteté',
      'showcase2Desc': 'Augmente les détails flous ou pixelisés via un scaling avancé et une amélioration de la netteté.',
      'showcase3Title': 'Portrait Bokeh',
      'showcase3Sub': 'Profondeur de flou DSLR',
      'showcase3Desc': 'Garde les sujets faciaux parfaitement nets tout en floutant les arrière-plans encombrés.',

      'cropRotate': 'Recadrer et Pivoter',
      'noImageSelected': 'Aucune image sélectionnée',
      'enhanceStrength': 'Force d\'Amélioration',
      'faceStrength': 'Force d\'Amélioration du Visage',
      'skinSmoothness': 'Douceur de la Peau',
      'bokehDepth': 'Profondeur du Bokeh',
      'upscaleSize': 'Taille de Mise à l\'échelle',
      'fastHd': 'HD Rapide',
      'ultraHd': 'Ultra HD',
      'upscaleNote': '4x crée des fichiers plus volumineux et peut prendre plus de temps, surtout sur l\'appareil.',

      'myCreations': 'Mes Créations',
      'noCreationsTitle': 'Aucune Création Enregistrée',
      'noCreationsSub': 'Vos chefs-d\'œuvre améliorés apparaîtront ici immédiatement après les avoir enregistrés dans votre galerie.',
      'enhancedPhoto': 'Photo Améliorée',
      'nSelected': 'Sélectionnés',
      'deleteSelected': 'Supprimer la Sélection',
      'deleteAllHistory': 'Supprimer Tout l\'Historique',
      'deleteAllTitle': 'Supprimer Toutes les Images Enregistrées ?',
      'deleteAllSub': 'Cela supprimera définitivement toutes vos créations améliorées par IA de l\'historique et du stockage. Action irréversible.',
      'deleteAll': 'Tout Supprimer',
      'deletedSelectedSnack': 'Photos sélectionnées supprimées avec succès.',
      'allDeletedSnack': 'Toutes les créations supprimées de l\'appareil.',
      'unknownDate': 'Date Inconnue',

      'resultTitle': 'Glisser Avant et Après',
      'freeExports': 'Exportations gratuites restantes:',
      'watermarkNotice': 'Les sauvegardes gratuites incluent un léger filigrane dans le coin.',
      'successTitle': 'Chef-d\'œuvre Enregistré !',
      'successSub': 'Votre photo améliorée se trouve dans votre galerie.',
      'excellent': 'Excellent',
      'limitReachedTitle': 'Limite gratuite atteinte',
      'limitReachedSub': 'Vous avez atteint la limite gratuite.',
      'later': 'Plus tard',
      'goPremium': 'Passer Premium',
      'imageMissing': 'Données d\'image manquantes. Relancez le traitement.',
      'openGallery': 'Ouvrir la Galerie',
      'saveFailedSnack': 'Échec de l\'enregistrement. Autorisez l\'accès aux Photos/Galerie.',

      'unlockPremium': 'Débloquer Premium',
      'premiumActive': '✓ Premium Actif',
      'freeSaves': 'Sauvegardes gratuites restantes aujourd\'hui:',
      'proBenefitTitle': 'Fonctionnalités PRO Incluses',
      'tapToCompare': 'TOUCHEZ POUR COMPARER 👆',
      'benefit1': 'Exportations Ultra HD sans compression',
      'benefit2': 'Pas de filigrane sur vos photos finales',
      'benefit3': 'Améliorations quotidiennes illimitées',
      'benefit4': 'Traitement prioritaire (Prochainement)',
      'benefit5': 'Traitement par lots pour plusieurs éléments (Prochainement)',
      'premiumTitle': 'Mise à niveau Premium',
      'devSettings': 'Paramètres de l\'API développeur',
      'enableCloud': 'Activer Cloud AI (Fal.ai)',
      'apiDesc': 'Insérez votre jeton privé de l\'API Fal.ai pour exécuter des modèles d\'IA haut de gamme sur des serveurs GPU cloud.',
      'apiHint': 'Collez le jeton Fal.ai ici...',
      'selectPlan': 'Sélectionnez un plan',
      'weekly': 'Hebdomadaire',
      'yearly': 'Premium Annuel',
      'lifetime': 'Ultra à vie',
      'bestValue': 'MEILLEURE VALEUR',
      'forever': 'POUR TOUJOURS',
      'payOnce': 'Payez une fois, utilisez pour toujours',
      'autoRenews': 'Renouvellement facile. Annulez à tout moment.',
      'localUnlockSnack': 'Succès ! Vous êtes maintenant membre PRO.',
      'billingNotice': 'La facturation Google Play est prête. Après avoir créé les produits (premium_weekly / premium_yearly / premium_lifetime) dans la Play Console, les achats réels s\'activent sans modification de code.',

      'batchStudio': 'Studio IA par Lots',
      'clearBatch': 'Vider le Lot',
      'batchEmptyTitle': 'Amélioration de Photos par Lots',
      'batchEmptySub': 'Sélectionnez plusieurs photos de votre bibliothèque pour les restaurer, agrandir ou coloriser en une seule file rapide !',
      'selectBatchPhotos': 'Sélectionner les Photos du Lot',
      'selectBatchAction': 'Sélectionner l\'Action IA :',
      'processNImages': 'Traiter les Images',
      'batchDoneMsg': 'Toutes les photos ont été traitées avec succès ! Vous pouvez les enregistrer dans votre galerie en un seul geste.',
      'saveAllGallery': 'Tout Enregistrer dans la Galerie',
      'batchSavedSnack': '🎉 Toutes les photos du lot ont été enregistrées dans votre galerie !',
      'processingQueue': 'Traitement de la file...',
      'batchKeepOpen': 'Traitement de votre file. Le cloud est utilisé pour Premium si disponible ; sinon traitement local. Gardez l\'app ouverte.',
      'premiumFeature': 'Fonctionnalité Premium',
      'premiumBatchSub': 'Le traitement IA par lots est exclusif aux PRO. Passez à Premium pour traiter plusieurs photos, enregistrer tous les résultats et utiliser le cloud.',
      'maybeLater': 'Peut-être Plus Tard',

      'aiProcessing': 'Traitement IA...',
      'phrase1': 'Analyse des pixels de l\'image...',
      'phrase2': 'Décompression de la résolution...',
      'phrase3': 'Détection des structures faciales...',
      'phrase4': 'Lissage des dégradés de peau...',
      'phrase5': 'Reconstruction des détails haute fréquence...',
      'phrase6': 'Application des hautes lumières...',
      'phrase7': 'Enregistrement de l\'exportation locale...',

      'desc_auto': 'Auto Enhance ajuste automatiquement la luminosité, le contraste et la saturation pour un équilibre parfait.',
      'desc_upscale': 'HD Upscale double la résolution (2x) à l\'aide d\'un algorithme d\'interpolation bicubique de précision.',
      'desc_face': 'Face Enhance lisse la peau pour atténuer les imperfections tout en gardant les yeux et la bouche bien nets.',
      'desc_denoise': 'Denoise réduit le grain numérique et le bruit des clichés sombres sans lisser les détails structurels.',
      'desc_unblur': 'Unblur corrige le flou de bougé et de mise au point pour redonner de la netteté à vos clichés.',
      'desc_colorize': 'Colorize B&W ajoute des couleurs chaudes et naturelles sur vos anciennes photos monochromes.',
      'desc_restore': 'Old Photo Restore corrige la décoloration sepia du papier et restaure la clarté d\'origine des détails.',
      'desc_cartoon': 'Cartoon Effect applique un filtre de dessin animé stylisé avec des contours marqués et des aplats colorés.',
      'desc_bg': 'Background Blur floute l\'arrière-plan de vos portraits en simulant le flou artistique (bokeh) des objectifs DSLR.',
      'desc_bg_cleanup': 'Background Cleanup remplace les distractions de fond par un fond de studio propre en utilisant un masquage intelligent centré.',

      'feat_auto_title': 'Amélioration Auto',
      'feat_auto_sub': 'Corrige couleurs, contraste et netteté',
      'feat_upscale_title': 'Mise à l\'échelle HD',
      'feat_upscale_sub': 'Agrandit 2x / 4x sans flou',
      'feat_face_title': 'Amélioration du Visage',
      'feat_face_sub': 'Lisse et affine les traits',
      'feat_denoise_title': 'Réduire le Bruit',
      'feat_denoise_sub': 'Supprime grain et pixelisation',
      'feat_unblur_title': 'Nettoyer Flou',
      'feat_unblur_sub': 'Corrige le flou de mouvement',
      'feat_colorize_title': 'Coloriser N&B',
      'feat_colorize_sub': 'Ajoute de la couleur aux vieilles photos',
      'feat_restore_title': 'Restaurer Ancienne',
      'feat_restore_sub': 'Répare photos fanées et sépia',
      'feat_cartoon_title': 'Effet Cartoon',
      'feat_cartoon_sub': 'Style pop art artistique',
      'feat_bg_title': 'Flou d\'Arrière-plan',
      'feat_bg_sub': 'Bokeh portrait professionnel',
      'feat_bg_cleanup_title': 'Nettoyer le Fond',
      'feat_bg_cleanup_sub': 'Supprime les distractions du fond',
    },
    'ur': {
      'tagline': 'AI فوٹو اینہانسر',
      'subTagline': 'اپنی پرانی اور دھندلی تصاویر کو سیکنڈوں میں ٹھیک کریں',

      'tabAiLab': 'AI لیب',
      'tabSaved': 'محفوظہ',
      'tabSettings': 'سیٹنگز',

      'chooseFeature': 'ٹول منتخب کریں',
      'onDevice': 'پروسیسنگ آپ کے فون پر ہوتی ہے، کسی انٹرنیٹ کی ضرورت نہیں۔',
      'gallery': 'گیلری',
      'camera': 'کیمرہ',
      'selectPhoto': 'شروع کرنے کے لیے ایک تصویر منتخب کریں',
      'importBlurry': 'تصویر منتخب کر کے جادو دیکھیں',
      'changePhoto': 'تصویر تبدیل کریں',
      'aiEditor': 'AI ایڈیٹر',
      'aiStudio': 'AI فوٹو اسٹوڈیو',
      'enhance': 'بہتر بنائیں',
      'compare': 'موازنہ کریں',
      'save': 'محفوظ کریں',
      'share': 'شیر کریں',
      'cancel': 'منسوخ',
      'closeBtn': 'بند کریں',
      'confirm': 'تصدیق کریں',
      'processingLabel': 'پروسیس ہو رہا ہے...',
      'next': 'آگے',
      'skip': 'چھوڑیں',
      'getStarted': 'شروع کریں',

      'chooseLanguage': 'زبان منتخب کریں',
      'searchLanguage': 'زبان تلاش کریں...',
      'noLanguagesFound': 'کوئی زبان نہیں ملی',

      'settingsTitle': 'سیٹنگز',
      'appLanguage': 'ایپ کی زبان',
      'shareFriends': 'دوستوں کو شیر کریں',
      'shareFriendsSub': 'PixelRevive کو پھیلائیں',
      'rateUs': 'ہمیں ریٹ دیں',
      'rateUsSub': 'پلے اسٹور پر ہماری مدد کریں',
      'terms': 'سروس کی شرائط',
      'termsSub': 'ہمارے قانونی اصول پڑھیں',
      'privacy': 'رازداری پالیسی',
      'privacySub': 'ہمارے ڈیٹا اصول پڑھیں',
      'appNameFull': 'PixelRevive AI فوٹو اسٹوڈیو',

      'onboardingTitle1': 'AI پرانی تصویر کی بحالی',
      'onboardingSub1': 'فوری طور پر مدھم رنگوں کو بحال کریں، پرانی پیلی رنگت کو ختم کریں، اور گہرے رنگوں کو واپس لائیں۔',
      'onboardingTitle2': 'الٹرا ایچ ڈی 4K اپ اسکیل',
      'onboardingSub2': 'دھندلی تصویر کو 4K ریزولوشن میں تبدیل کریں۔',
      'onboardingTitle3': 'DSLR بیک گراؤنڈ بلر',
      'onboardingSub3': 'پس منظر کو دھندلا کر کے چہرے کو نمایاں کریں۔',

      'cloudBadge': 'محفوظ کلاؤڈ AI پروسیسنگ ⚡',
      'onDeviceBadge': 'ڈیوائس پر AI پروسیسنگ',
      'cloudHeadline': 'الٹرا ایچ ڈی چہرہ بحالی\nکلاؤڈ GPUs سے چلائی گئی',
      'cloudDesc': 'تیز رفتار سرورز پر جدید ماڈلز چلا کر شاندار تفصیلات حاصل کریں۔',
      'onDeviceHeroDesc': 'پکسل شدہ، دھندلی یا بلیک اینڈ وائٹ تصاویر کو کہیں اپ لوڈ کیے بغیر اپنے فون پر بہتر بنائیں۔',
      'batchTitle': 'بیچ AI بہتری',
      'batchSub': 'یکساتھ متعدد تصاویر پروسیس کریں',
      'showcaseTitle': 'انٹرایکٹو گیلری',
      'showcase1Title': 'خاندانی محافظ',
      'showcase1Sub': 'رنگین کریں اور خراشیں ہٹائیں',
      'showcase1Desc': 'پرانی پیلی تصاویر کو متوازن رنگ اور واضح کونٹراسٹ کے ساتھ زندہ کرتا ہے۔',
      'showcase2Title': 'کرسٹل چہرہ',
      'showcase2Sub': 'ایچ ڈی اسکیلنگ اور تیز دھار',
      'showcase2Desc': 'اعلیٰ ذیلی پکسل اسکیلنگ سے دھندلی تفصیلات کو بڑھاتا ہے۔',
      'showcase3Title': 'بوکے پورٹریٹ',
      'showcase3Sub': 'DSLR وِگنیٹ بلر گہرائی',
      'showcase3Desc': 'چہرے کو مکمل فوکس میں رکھتے ہوئے پس منظر کو نرمی سے دھندلا کرتا ہے۔',

      'cropRotate': 'کاپ اور گھمائیں',
      'noImageSelected': 'کوئی تصویر منتخب نہیں',
      'enhanceStrength': 'بہتری کی طاقت',
      'faceStrength': 'چہرہ بہتری کی طاقت',
      'skinSmoothness': 'جلد کی نرمی',
      'bokehDepth': 'بیک گراؤنڈ بوکے گہرائی',
      'upscaleSize': 'اپ اسکیل سائز',
      'fastHd': 'تیز HD',
      'ultraHd': 'الٹرا HD',
      'upscaleNote': '4x بڑی فائلز بناتا ہے اور زیادہ وقت لگا سکتا ہے۔',

      'myCreations': 'میری تخلیقات',
      'noCreationsTitle': 'کوئی محفوظ تخلیق نہیں',
      'noCreationsSub': 'آپ کی بہتر کی گئی تصاویر گیلری میں محفوظ کرنے کے فوراً بعد یہاں نظر آئیں گی۔',
      'enhancedPhoto': 'بہتر تصویر',
      'nSelected': 'منتخب',
      'deleteSelected': 'منتخب حذف کریں',
      'deleteAllHistory': 'پوری ہسٹری حذف کریں',
      'deleteAllTitle': 'تمام محفوظ تصاویر حذف کریں؟',
      'deleteAllSub': 'یہ آپ کی تمام بہتر کی گئی تخلیقات کو ہسٹری اور اسٹوریج سے مستقل طور پر حذف کر دے گا۔ یہ عمل واپس نہیں ہو سکتا۔',
      'deleteAll': 'سب حذف کریں',
      'deletedSelectedSnack': 'منتخب تصاویر کامیابی سے حذف ہو گئیں۔',
      'allDeletedSnack': 'تمام تخلیقات ڈیوائس سے حذف ہو گئیں۔',
      'unknownDate': 'نامعلوم تاریخ',

      'resultTitle': 'موازنہ سوائپ کریں',
      'freeExports': 'مفت برآمدات باقی ہیں:',
      'watermarkNotice': 'مفت بچتوں میں کونے پر ایک چھوٹا واٹر مارک شامل ہے۔',
      'successTitle': 'شہ پارہ محفوظ ہو گیا!',
      'successSub': 'تصویر آپ کے فون کی گیلری میں محفوظ کر دی گئی ہے۔',
      'excellent': 'بہترین',
      'limitReachedTitle': 'مفت حد ختم ہو گئی',
      'limitReachedSub': 'آج کی مفت بچتیں ختم ہو گئیں۔',
      'later': 'بعد میں',
      'goPremium': 'پریمیم حاصل کریں',
      'imageMissing': 'تصویر کا ڈیٹا غائب ہے۔ دوبارہ پروسیس کریں۔',
      'openGallery': 'گیلری کھولیں',
      'saveFailedSnack': 'گیلری میں محفوظ کرنے میں ناکامی۔ فوٹوز/گیلری تک رسائی دیں۔',

      'unlockPremium': 'پریمیم حاصل کریں',
      'premiumActive': '✓ پریمیم فعال ہے',
      'freeSaves': 'آج کے مفت بچاؤ باقی ہیں:',
      'proBenefitTitle': 'پرو خصوصیات شامل ہیں',
      'tapToCompare': 'موازنہ کے لیے دبائیں 👆',
      'benefit1': 'بغیر کسی کمپریشن کے الٹرا ایچ ڈی ایکسپورٹ',
      'benefit2': 'آپ کی آخری تصاویر پر کوئی واٹر مارک نہیں ہے',
      'benefit3': 'لامحدود روزانہ تصویر میں بہتری',
      'benefit4': 'اعلیٰ ترجیحی پروسیسنگ (بہت جلد)',
      'benefit5': 'ایک ساتھ متعدد تصاویر کی پروسیسنگ (بہت جلد)',
      'premiumTitle': 'پریمیم اپ گریڈ',
      'devSettings': 'ڈیولپر API سیٹنگز',
      'enableCloud': 'کلاؤڈ AI فعال کریں (Fal.ai)',
      'apiDesc': 'ہائی اسپیڈ کلاؤڈ سرورز پر بہترین ماڈلز چلانے کے لیے اپنا ذاتی Fal.ai ٹوکن درج کریں۔',
      'apiHint': 'یہاں Fal.ai ٹوکن پیسٹ کریں...',
      'selectPlan': 'ایک پلان منتخب کریں',
      'weekly': 'ہفتہ وار',
      'yearly': 'سالانہ پریمیم',
      'lifetime': 'لائف ٹائم الٹرا',
      'bestValue': 'بہترین قیمت',
      'forever': 'ہمیشہ کے لیے',
      'payOnce': 'ایک بار ادا کریں، ہمیشہ استعمال کریں',
      'autoRenews': 'آسانی سے تجدید ہوتی ہے۔ کبھی بھی منسوخ کریں۔',
      'localUnlockSnack': 'کامیابی! آپ اب PRO ممبر ہیں۔',
      'billingNotice': 'گوگل پلے بلنگ تیار ہے۔ پلے کنسول میں پراڈکٹس (premium_weekly / premium_yearly / premium_lifetime) بنانے کے بعد، اصلی خریداری کوڈ میں کوئی تبدیلی کیے بغیر فعال ہو جائے گی۔',

      'batchStudio': 'بیچ AI اسٹوڈیو',
      'clearBatch': 'بیچ صاف کریں',
      'batchEmptyTitle': 'بیچ فوٹو بہتری',
      'batchEmptySub': 'اپنی لائبریری سے متعدد تصاویر منتخب کریں اور ایک ہی تیز رفتار قطار میں بحال کریں!',
      'selectBatchPhotos': 'بیچ تصاویر منتخب کریں',
      'selectBatchAction': 'AI بیچ عمل منتخب کریں:',
      'processNImages': 'تصاویر پروسیس کریں',
      'batchDoneMsg': 'تمام تصاویر کامیابی سے پروسیس ہو گئیں! اب انہیں ایک ٹیپ میں محفوظ کریں۔',
      'saveAllGallery': 'سب گیلری میں محفوظ کریں',
      'batchSavedSnack': '🎉 تمام بیچ تصاویر گیلری میں محفوظ ہو گئیں!',
      'processingQueue': 'قطار پروسیس ہو رہی ہے...',
      'batchKeepOpen': 'آپ کی قطار پروسیس ہو رہی ہے۔ پریمیم کے لیے کلاؤڈ استعمال ہوتا ہے؛ بصورت دیگر مقامی پروسیسنگ۔ ایپ کھلی رکھیں۔',
      'premiumFeature': 'پریمیم فیچر',
      'premiumBatchSub': 'بیچ AI پروسیسنگ PRO کے لیے مخصوص ہے۔ متعدد تصاویر پروسیس کرنے کے لیے پریمیم حاصل کریں۔',
      'maybeLater': 'شاید بعد میں',

      'aiProcessing': 'AI پروسیس ہو رہا ہے...',
      'phrase1': 'تصویر کے پکسلز اسکین ہو رہے ہیں...',
      'phrase2': 'ریذولوشن ڈی کمپریس ہو رہی ہے...',
      'phrase3': 'چہرے کی ساخت کی پہچان ہو رہی ہے...',
      'phrase4': 'جلد کے گریڈینٹس ہموار ہو رہے ہیں...',
      'phrase5': 'تفصیلات کی تعمیر نو ہو رہی ہے...',
      'phrase6': 'ٹوننگ لگائی جا رہی ہے...',
      'phrase7': 'محفوظ مقامی ایکسپورٹ ہو رہا ہے...',

      'desc_auto': 'موبائل پر روشنی اور رنگوں کو آٹو ایڈجسٹ کریں۔',
      'desc_upscale': 'تصویر کی ریزولیوشن کو 2x یا 4x تک بڑھائیں۔',
      'desc_face': 'چہرے کی جھریاں دور کر کے ملامح کو واضح کریں۔',
      'desc_denoise': 'اندھیرے والی تصاویر کا دانہ دار پن دور کریں۔',
      'desc_unblur': 'تصویر کا دھندلا پن دور کریں۔',
      'desc_colorize': 'پرانی تصاویر کو رنگین بنائیں۔',
      'desc_restore': 'پرانی تصویروں کو بحال کریں۔',
      'desc_cartoon': 'تصویر کو کارٹون آرٹ بنائیں۔',
      'desc_bg': 'بیک گراؤنڈ بلر کریں۔',
      'desc_bg_cleanup': 'بیک گراؤنڈ کلین اپ پس منظر کو اسٹوڈیو بیک گراؤنڈ سے تبدیل کرتی ہے۔',

      'feat_auto_title': 'آٹو بہتری',
      'feat_auto_sub': 'رنگ، کونٹراسٹ، تیزی ٹھیک کریں',
      'feat_upscale_title': 'ایچ ڈی اپ اسکیل',
      'feat_upscale_sub': '2x / 4x دھندلاپھ بڑھائیں',
      'feat_face_title': 'چہرہ بہتری',
      'feat_face_sub': 'چہرے نرم اور واضح کریں',
      'feat_denoise_title': 'شور ہٹائیں',
      'feat_denoise_sub': 'دانہ اور شور ہٹائیں',
      'feat_unblur_title': 'دھندلاپھ دور',
      'feat_unblur_sub': 'موشن بلر کم کریں',
      'feat_colorize_title': 'رنگین بنائیں',
      'feat_colorize_sub': 'پرانی تصاویر کو رنگ دیں',
      'feat_restore_title': 'پرانی تصویر بحال',
      'feat_restore_sub': 'پیلی اور خراشیں ٹھیک کریں',
      'feat_cartoon_title': 'کارٹون اثر',
      'feat_cartoon_sub': 'آرٹسٹک رنگ اور کنارے',
      'feat_bg_title': 'بیک گراؤنڈ بلر',
      'feat_bg_sub': 'پس منظر دھندلا، چہرہ واضح',
      'feat_bg_cleanup_title': 'بیک گراؤنڈ کلین',
      'feat_bg_cleanup_sub': 'پس منظر کے فاصلے ہٹائیں',
    },
    'ar': {
      'tagline': 'محسن صور احترافي بالذكاء الاصطناعي',
      'subTagline': 'استرجع ذكرياتك القديمة وقم بتحسينها وإزالة التشويش فورًا',

      'tabAiLab': 'مختبر الذكاء',
      'tabSaved': 'المحفوظات',
      'tabSettings': 'الإعدادات',

      'chooseFeature': 'اختر ميزة الذكاء الاصطناعي',
      'onDevice': 'معالجة فورية على الجهاز. لا يلزم الاتصال بالإنترنت.',
      'gallery': 'المعرض',
      'camera': 'الكاميرا',
      'selectPhoto': 'حدد صورة للبدء',
      'importBlurry': 'قم باستيراد صورة قديمة أو ضبابية لتجربة فلاتر الذكاء الاصطناعي',
      'changePhoto': 'تغيير الصورة',
      'aiEditor': 'محرر الذكاء الاصطناعي',
      'aiStudio': 'استوديو صور بالذكاء الاصطناعي',
      'enhance': 'تحسين',
      'compare': 'مقارنة',
      'save': 'حفظ',
      'share': 'مشاركة',
      'cancel': 'إلغاء',
      'closeBtn': 'إغلاق',
      'confirm': 'تأكيد',
      'processingLabel': 'جارٍ المعالجة...',
      'next': 'التالي',
      'skip': 'تخطي',
      'getStarted': 'ابدأ الآن',

      'chooseLanguage': 'اختر اللغة',
      'searchLanguage': 'ابحث عن لغة...',
      'noLanguagesFound': 'لم يتم العثور على لغات',

      'settingsTitle': 'الإعدادات',
      'appLanguage': 'لغة التطبيق',
      'shareFriends': 'شارك مع الأصدقاء',
      'shareFriendsSub': 'انشر تطبيق PixelRevive',
      'rateUs': 'قيّمنا',
      'rateUsSub': 'ادعمنا على متجر Play',
      'terms': 'شروط الخدمة',
      'termsSub': 'اقرأ إرشاداتنا القانونية',
      'privacy': 'سياسة الخصوصية',
      'privacySub': 'اقرأ قواعد التعامل مع البيانات',
      'appNameFull': 'استوديو PixelRevive للصور بالذكاء الاصطناعي',

      'onboardingTitle1': 'استعادة الصور القديمة بالذكاء الاصطناعي',
      'onboardingSub1': 'استرجع الألوان الباهتة فورًا، وأزل درجات اللون البني القديمة، واستعد التباين العميق.',
      'onboardingTitle2': 'ترقية الجودة إلى Ultra HD 4K',
      'onboardingSub2': 'قم بتكبير صورك منخفضة الدقة أو الضبابية حتى 4 مرات بحواف حادة وتفاصيل واضحة.',
      'onboardingTitle3': 'تمويه الخلفية الاحترافي',
      'onboardingSub3': 'قم بمحاكاة بوكيه الكاميرات الاحترافية. ركز على العناصر وقم بتمويه الخلفيات المشتتة.',

      'cloudBadge': 'معالجة ذكاء اصطناعي سحابية آمنة ⚡',
      'onDeviceBadge': 'معالجة ذكاء اصطناعي على الجهاز',
      'cloudHeadline': 'إعادة بناء الوجه بدقة فائقة\nمدعومة بوحدات معالجة سحابية',
      'cloudDesc': 'تشغيل نماذج متطورة على خوادم عالية السرعة للحصول على تفاصيل بلورية مذهلة.',
      'onDeviceHeroDesc': 'أعد الحياة إلى الصور البكسلية أو الضبابية أو الأبيض والأسود محليًا على هاتفك دون رفعها لأي مكان.',
      'batchTitle': 'تحسين ذكاء اصطناعي بالجملة',
      'batchSub': 'عالج صورًا متعددة في نفس الوقت فورًا',
      'showcaseTitle': 'معرض تفاعلي',
      'showcase1Title': 'أرشيف العائلة',
      'showcase1Sub': 'تلوين وإزالة الخدوش',
      'showcase1Desc': 'يعيد الحياة إلى الصور القديمة الباهتة بألوان واقعية وتباين حاد.',
      'showcase2Title': 'وجه بلوري',
      'showcase2Sub': 'تكبير عالي الدقة وحدود حادة',
      'showcase2Desc': 'يعزز التفاصيل الضبابية باستخدام تكبير البكسل الفرعي المتقدم.',
      'showcase3Title': 'بورتريه بوكيه',
      'showcase3Sub': 'عمق تمويه احترافي',
      'showcase3Desc': 'يحافظ على تركيز الوجه مع تمويه ناعم للخلفيات المزدحمة.',

      'cropRotate': 'اقتصاص وتدوير',
      'noImageSelected': 'لم يتم تحديد صورة',
      'enhanceStrength': 'قوة التحسين',
      'faceStrength': 'قوة تحسين الوجه',
      'skinSmoothness': 'نعومة البشرة',
      'bokehDepth': 'عمق تمويه الخلفية',
      'upscaleSize': 'حجم التكبير',
      'fastHd': 'HD سريع',
      'ultraHd': 'Ultra HD',
      'upscaleNote': 'حجم 4x ينتج ملفات أكبر وقد يستغرق وقتًا أطول، خاصة على الجهاز.',

      'myCreations': 'إبداعاتي',
      'noCreationsTitle': 'لا توجد إبداعات محفوظة',
      'noCreationsSub': 'ستظهر تحفتك الفنية المحسنة هنا فور حفظها في معرضك.',
      'enhancedPhoto': 'صورة محسّنة',
      'nSelected': 'محدد',
      'deleteSelected': 'حذف المحدد',
      'deleteAllHistory': 'حذف كامل السجل',
      'deleteAllTitle': 'حذف جميع الصور المحفوظة؟',
      'deleteAllSub': 'سيؤدي هذا إلى حذف جميع إبداعاتك المحسّنة بالذكاء الاصطناعي نهائيًا من السجل والتخزين. لا يمكن التراجع عن هذا الإجراء.',
      'deleteAll': 'حذف الكل',
      'deletedSelectedSnack': 'تم حذف الصور المحددة بنجاح.',
      'allDeletedSnack': 'تم حذف جميع الإبداعات من الجهاز.',
      'unknownDate': 'تاريخ غير معروف',

      'resultTitle': 'مقارنة بالسحب قبل وبعد',
      'freeExports': 'مرات التصدير المجانية المتبقية:',
      'watermarkNotice': 'الحفظ المجاني يتضمن علامة مائية صغيرة في الزاوية.',
      'successTitle': 'تم حفظ التحفة الفنية!',
      'successSub': 'تم حفظ صورتك المحسنة بنجاح في مجلد معرض الصور بهاتفك.',
      'excellent': 'ممتاز',
      'limitReachedTitle': 'تم الوصول إلى الحد الأقصى',
      'limitReachedSub': 'لقد استهلكت جميع المرات المجانية لليوم. قم بترقية العضوية لتنزيلات غير محدودة.',
      'later': 'لاحقًا',
      'goPremium': 'الذهاب للمميز',
      'imageMissing': 'بيانات الصورة مفقودة. أعد المعالجة.',
      'openGallery': 'فتح المعرض',
      'saveFailedSnack': 'فشل الحفظ في المعرض. اسمح بالوصول إلى الصور/المعرض.',

      'unlockPremium': 'فتح العضوية المميزة',
      'premiumActive': '✓ العضوية المميزة نشطة',
      'freeSaves': 'المرات المجانية المتبقية للحفظ اليوم:',
      'proBenefitTitle': 'الميزات الاحترافية المضمنة',
      'tapToCompare': 'انقر للمقارنة 👆',
      'benefit1': 'تصدير بجودة Ultra HD بدون أي ضغط',
      'benefit2': 'لا توجد علامة مائية على صورك النهائية',
      'benefit3': 'تحسينات صور يومية غير محدودة',
      'benefit4': 'معالجة ذات أولوية عالية (قريبًا)',
      'benefit5': 'معالجة الدفعات لعدة عناصر (قريبًا)',
      'premiumTitle': 'الترقية المميزة',
      'devSettings': 'إعدادات المطور الخاصة بـ API',
      'enableCloud': 'تفعيل الذكاء الاصطناعي السحابي (Fal.ai)',
      'apiDesc': 'أدخل رمز API الخاص بك لـ Fal.ai لتشغيل أقوى النماذج على خوادم سحابية فائقة السرعة.',
      'apiHint': 'ألصق رمز Fal.ai هنا...',
      'selectPlan': 'اختر خطة الاشتراك',
      'weekly': 'أسبوعي',
      'yearly': 'مميز سنوي',
      'lifetime': 'عضوية مدى الحياة',
      'bestValue': 'أفضل قيمة',
      'forever': 'للأبد',
      'payOnce': 'ادفع مرة واحدة، واستخدم للأبد',
      'autoRenews': 'يتجدد بسهولة. ألغِ في أي وقت.',
      'localUnlockSnack': 'نجاح! أنت الآن عضو PRO.',
      'billingNotice': 'نظام الدفع عبر Google Play جاهز. بعد إنشاء المنتجات (premium_weekly / premium_yearly / premium_lifetime) في Play Console، تُفعَّل عمليات الشراء الحقيقية دون أي تغيير في الكود.',

      'batchStudio': 'استوديو الذكاء الاصطناعي بالجملة',
      'clearBatch': 'مسح الدفعة',
      'batchEmptyTitle': 'تحسين الصور بالجملة',
      'batchEmptySub': 'حدد صورًا متعددة من مكتبتك لاستعادتها أو تكبيرها أو تلوينها في قائمة سريعة واحدة!',
      'selectBatchPhotos': 'حدد صور الدفعة',
      'selectBatchAction': 'اختر إجراء الذكاء الاصطناعي:',
      'processNImages': 'معالجة الصور',
      'batchDoneMsg': 'تمت معالجة جميع الصور بنجاح! يمكنك الآن حفظها في معرضك بنقرة واحدة.',
      'saveAllGallery': 'حفظ الكل في المعرض',
      'batchSavedSnack': '🎉 تم حفظ جميع صور الدفعة في معرضك بنجاح!',
      'processingQueue': 'جارٍ معالجة القائمة...',
      'batchKeepOpen': 'جارٍ معالجة قائمتك. تُستخدم السحابة للمميز عند توفرها؛ وإلا المعالجة المحلية. أبقِ التطبيق مفتوحًا.',
      'premiumFeature': 'ميزة مميزة',
      'premiumBatchSub': 'المعالجة بالجملة حصرية لـ PRO. قم بالترقية إلى Premium لمعالجة صور متعددة وحفظ كل النتائج.',
      'maybeLater': 'ربما لاحقًا',

      'aiProcessing': 'جارٍ المعالجة بالذكاء الاصطناعي...',
      'phrase1': 'جارٍ مسح بكسلات الصورة...',
      'phrase2': 'جارٍ فك ضغط الدقة...',
      'phrase3': 'جارٍ اكتشاف بنية الوجه...',
      'phrase4': 'جارٍ تنعيم تدرجات البشرة...',
      'phrase5': 'جارٍ إعادة بناء التفاصيل...',
      'phrase6': 'جارٍ تطبيق التدرج اللوني...',
      'phrase7': 'جارٍ حفظ التصدير المحلي...',

      'desc_auto': 'تقوم ميزة Auto Enhance بضبط السطوع والتباين تلقائيًا وإبراز الألوان الباهتة.',
      'desc_upscale': 'تضاعف ميزة HD Upscale دقة الصورة مرتين أو أربعة أضعاف باستخدام خوارزمية تكبير ذكية.',
      'desc_face': 'تنعم Face Enhance البشرة وتوضح تفاصيل العينين والشفتين بدقة.',
      'desc_denoise': 'تزيل ميزة Denoise الحبيبات الرقمية مع الحفاظ على وضوح التفاصيل.',
      'desc_unblur': 'تعالج ميزة Unblur ضبابية الحركة والاهتزاز.',
      'desc_colorize': 'تضيف ميزة Colorize B&W ألوانًا دافئة وواقعية على صورك القديمة.',
      'desc_restore': 'تزيل ميزة Old Photo Restore اصفرار الورق وتعيد التباين الغني.',
      'desc_cartoon': 'تحول ميزة Cartoon Effect صورك إلى لوحة كرتونية فنية.',
      'desc_bg': 'تقوم ميزة Background Blur بتمويه خلفية صورك الشخصية باحترافية.',
      'desc_bg_cleanup': 'تستبدل Background Cleanup مشتتات الخلفية بخلفية استوديو نظيفة.',

      'feat_auto_title': 'تحسين تلقائي',
      'feat_auto_sub': 'يصحح الألوان والتباين والحدة',
      'feat_upscale_title': 'تكبير HD',
      'feat_upscale_sub': 'تكبير 2x / 4x بدون تشويش',
      'feat_face_title': 'تحسين الوجه',
      'feat_face_sub': 'تنعيم وتوضيح الملامح',
      'feat_denoise_title': 'إزالة التشويش',
      'feat_denoise_sub': 'يزيل الحبيبات والضوضاء',
      'feat_unblur_title': 'إزالة الضبابية',
      'feat_unblur_sub': 'يقلل ضبابية الحركة',
      'feat_colorize_title': 'تلوين أبيض وأسود',
      'feat_colorize_sub': 'أضف لونًا للصور القديمة',
      'feat_restore_title': 'استعادة صورة قديمة',
      'feat_restore_sub': 'يصلح الباهت والبني والخدوش',
      'feat_cartoon_title': 'تأثير كرتوني',
      'feat_cartoon_sub': 'فن الحواف والألوان',
      'feat_bg_title': 'تمويه الخلفية',
      'feat_bg_sub': 'خلفية مموهة ووجه حاد',
      'feat_bg_cleanup_title': 'تنظيف الخلفية',
      'feat_bg_cleanup_sub': 'يزيل تشتيت الخلفية',
    },
    'de': {
      'tagline': 'Professioneller KI-Foto-Verbesserer',
      'subTagline': 'Stellen Sie alte Erinnerungen sofort wieder her, verbessern und schärfen Sie sie',

      'tabAiLab': 'KI-Labor',
      'tabSaved': 'Gespeichert',
      'tabSettings': 'Einstellungen',

      'chooseFeature': 'KI-Funktion wählen',
      'onDevice': 'Sofortige Offline-Verarbeitung. Kein Internet erforderlich.',
      'gallery': 'Galerie',
      'camera': 'Kamera',
      'selectPhoto': 'Wählen Sie ein Foto aus',
      'importBlurry': 'Importieren Sie ein unscharfes Foto, um KI-Filter zu testen',
      'changePhoto': 'Foto ändern',
      'aiEditor': 'KI-Editor',
      'aiStudio': 'KI-Fotostudio',
      'enhance': 'Verbessern',
      'compare': 'Vergleichen',
      'save': 'Speichern',
      'share': 'Teilen',
      'cancel': 'Abbrechen',
      'closeBtn': 'Schließen',
      'confirm': 'Bestätigen',
      'processingLabel': 'Verarbeitung...',
      'next': 'Weiter',
      'skip': 'Überspringen',
      'getStarted': 'Loslegen',

      'chooseLanguage': 'Sprache wählen',
      'searchLanguage': 'Sprache suchen...',
      'noLanguagesFound': 'Keine Sprachen gefunden',

      'settingsTitle': 'Einstellungen',
      'appLanguage': 'App-Sprache',
      'shareFriends': 'Mit Freunden teilen',
      'shareFriendsSub': 'Erzählen Sie von PixelRevive',
      'rateUs': 'Bewerten Sie uns',
      'rateUsSub': 'Unterstützen Sie uns im Play Store',
      'terms': 'Nutzungsbedingungen',
      'termsSub': 'Lesen Sie unsere rechtlichen Richtlinien',
      'privacy': 'Datenschutzrichtlinie',
      'privacySub': 'Lesen Sie unsere Datenregeln',
      'appNameFull': 'PixelRevive KI-Fotostudio',

      'onboardingTitle1': 'KI-Fotowiederherstellung',
      'onboardingSub1': 'Stellen Sie verblasste Farben sofort wieder her und bringen Sie tiefe Kontraste zurück.',
      'onboardingTitle2': 'Ultra HD 4K Skalierung',
      'onboardingSub2': 'Vergrößern Sie unscharfe oder pixelige Bilder um das bis zu 4-Fache mit klaren Kanten.',
      'onboardingTitle3': 'DSLR Background-Weichzeichnung',
      'onboardingSub3': 'Simulieren Sie professionelles Kamera-Bokeh. Fokussieren Sie Ihre Motive.',

      'cloudBadge': 'SICHERE KI-CLOUD-VERARBEITUNG ⚡',
      'onDeviceBadge': 'KI-VERARBEITUNG AUF DEM GERÄT',
      'cloudHeadline': 'Ultra HD Gesichtsrekonstruktion\nAngetrieben von Cloud-GPUs',
      'cloudDesc': 'Ausführung modernster Modelle auf Hochgeschwindigkeits-Servern für atemberaubende kristalline Details.',
      'onDeviceHeroDesc': 'Verleihen Sie pixeligen, unscharfen oder Schwarz-Weiß-Fotos lokal auf Ihrem Telefon neues Leben, ohne sie hochzuladen.',
      'batchTitle': 'KI-Stapelverbesserung',
      'batchSub': 'Mehrere Bilder parallel sofort verarbeiten',
      'showcaseTitle': 'Interaktive Galerie',
      'showcase1Title': 'Familienarchivar',
      'showcase1Sub': 'Kolorieren und Kratzer entfernen',
      'showcase1Desc': 'Erweckt verblasste Sepia-Porträts mit lebendigen Farben und knackigen Kontrasten zum Leben.',
      'showcase2Title': 'Kristallines Gesicht',
      'showcase2Sub': 'HD-Hochskalierung & Kanten schärfen',
      'showcase2Desc': 'Erhöht unscharfe Details durch fortschrittliche Subpixel-Skalierung und Schärfung.',
      'showcase3Title': 'Bokeh-Porträt',
      'showcase3Sub': 'DSLR-Vignettierungs-Tiefenunschärfe',
      'showcase3Desc': 'Hält Gesichter perfekt scharf, während unübersichtliche Hintergründe weichgezeichnet werden.',

      'cropRotate': 'Zuschneiden & Drehen',
      'noImageSelected': 'Kein Bild ausgewählt',
      'enhanceStrength': 'Verbesserungsstärke',
      'faceStrength': 'Gesichtsverbesserungsstärke',
      'skinSmoothness': 'Hautglättung',
      'bokehDepth': 'Hintergrund-Bokeh-Tiefe',
      'upscaleSize': 'Hochskalierungsgröße',
      'fastHd': 'Schnelles HD',
      'ultraHd': 'Ultra HD',
      'upscaleNote': '4x erstellt größere Dateien und kann länger dauern, besonders auf dem Gerät.',

      'myCreations': 'Meine Kreationen',
      'noCreationsTitle': 'Keine gespeicherten Kreationen',
      'noCreationsSub': 'Ihre verbesserten Meisterwerke erscheinen hier sofort nach dem Speichern in Ihrer Galerie.',
      'enhancedPhoto': 'Verbessertes Foto',
      'nSelected': 'Ausgewählt',
      'deleteSelected': 'Auswahl löschen',
      'deleteAllHistory': 'Gesamten Verlauf löschen',
      'deleteAllTitle': 'Alle gespeicherten Bilder löschen?',
      'deleteAllSub': 'Dadurch werden alle Ihre mit KI verbesserten Kreationen dauerhaft aus Verlauf und Speicher gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.',
      'deleteAll': 'Alle löschen',
      'deletedSelectedSnack': 'Ausgewählte Fotos erfolgreich gelöscht.',
      'allDeletedSnack': 'Alle Kreationen vom Gerät gelöscht.',
      'unknownDate': 'Unbekanntes Datum',

      'resultTitle': 'Vorher & Nachher wischen',
      'freeExports': 'Verbleibende freie Exporte:',
      'watermarkNotice': 'Kostenlose Speicherungen enthalten ein kleines Wasserzeichen in der Ecke.',
      'successTitle': 'Meisterwerk gespeichert!',
      'successSub': 'Ihr verbessertes Foto wurde erfolgreich im Galerieordner gespeichert.',
      'excellent': 'Ausgezeichnet',
      'limitReachedTitle': 'Kostenloses Limit erreicht',
      'limitReachedSub': 'Sie haben heute alle kostenlosen Speicherkontingente aufgebraucht. Upgraden Sie für unbegrenzte Exporte.',
      'later': 'Später',
      'goPremium': 'Zu Premium wechseln',
      'imageMissing': 'Bilddaten fehlen. Bitte erneut verarbeiten.',
      'openGallery': 'Galerie öffnen',
      'saveFailedSnack': 'Speichern in der Galerie fehlgeschlagen. Erlauben Sie Fotos/Galerie-Zugriff.',

      'unlockPremium': 'Premium freischalten',
      'premiumActive': '✓ Premium Aktiv',
      'freeSaves': 'Verbleibende freie Speicherungen heute:',
      'proBenefitTitle': 'PRO-Funktionen Enthalten',
      'tapToCompare': 'ZUM VERGLEICHEN TIPPEN 👆',
      'benefit1': 'Ultra HD-Exporte ohne Komprimierung',
      'benefit2': 'Kein Wasserzeichen auf Ihren fertigen Fotos',
      'benefit3': 'Unbegrenzte tägliche Foto-Verbesserungen',
      'benefit4': 'Prioritäre Verarbeitung (In Kürze)',
      'benefit5': 'Stapelverarbeitung für mehrere Bilder (In Kürze)',
      'premiumTitle': 'Premium-Upgrade',
      'devSettings': 'Entwickler-API-Einstellungen',
      'enableCloud': 'Cloud-KI aktivieren (Fal.ai)',
      'apiDesc': 'Fügen Sie Ihren privaten Fal.ai-API-Token ein, um erstklassige KI-Modelle auf schnellen Cloud-Servern auszuführen.',
      'apiHint': 'Fal.ai-Token hier einfügen...',
      'selectPlan': 'Wählen Sie einen Plan',
      'weekly': 'Wöchentlich',
      'yearly': 'Jährliches Premium',
      'lifetime': 'Lebenslanges Ultra',
      'bestValue': 'BESTER WERT',
      'forever': 'FÜR IMMER',
      'payOnce': 'Einmal zahlen, für immer nutzen',
      'autoRenews': 'Einfache Verlängerung. Jederzeit kündbar.',
      'localUnlockSnack': 'Erfolg! Du bist jetzt PRO-Mitglied.',
      'billingNotice': 'Die Google Play-Abrechnung ist eingerichtet. Nach dem Erstellen der Produkte (premium_weekly / premium_yearly / premium_lifetime) in der Play Console werden echte Käufe ohne Codeänderung aktiviert.',

      'batchStudio': 'KI-Stapelstudio',
      'clearBatch': 'Stapel leeren',
      'batchEmptyTitle': 'Stapel-Fotoverbesserung',
      'batchEmptySub': 'Wählen Sie mehrere Fotos aus Ihrer Bibliothek aus, um sie in einer einzigen Hochgeschwindigkeits-Warteschlange wiederherzustellen!',
      'selectBatchPhotos': 'Stapelfotos auswählen',
      'selectBatchAction': 'KI-Stapelaktion wählen:',
      'processNImages': 'Bilder verarbeiten',
      'batchDoneMsg': 'Alle Fotos erfolgreich verarbeitet! Sie können sie jetzt mit einem Tippen in Ihrer Galerie speichern.',
      'saveAllGallery': 'Alle in Galerie speichern',
      'batchSavedSnack': '🎉 Alle Stapelfotos erfolgreich in Ihrer Galerie gespeichert!',
      'processingQueue': 'Warteschlange wird verarbeitet...',
      'batchKeepOpen': 'Ihre Warteschlange wird verarbeitet. Für Premium wird Cloud verwendet; sonst lokale Verarbeitung. App geöffnet lassen.',
      'premiumFeature': 'Premium-Funktion',
      'premiumBatchSub': 'Stapel-KI-Verarbeitung ist exklusiv für PRO. Upgraden Sie auf Premium, um mehrere Fotos zu verarbeiten.',
      'maybeLater': 'Vielleicht später',

      'aiProcessing': 'KI-Verarbeitung...',
      'phrase1': 'Bild-Pixel werden gescannt...',
      'phrase2': 'Auflösung wird dekomprimiert...',
      'phrase3': 'Gesichtsstrukturen werden erkannt...',
      'phrase4': 'Hautverläufe werden geglättet...',
      'phrase5': 'Details werden rekonstruiert...',
      'phrase6': 'Tonung wird angewendet...',
      'phrase7': 'Sicherer lokaler Export wird gespeichert...',

      'desc_auto': 'Auto Enhance optimiert Helligkeit, Kontrast und Sättigung für ein perfekt ausgewogenes Foto.',
      'desc_upscale': 'HD Upscale verdoppelt oder vervierfacht die Auflösung mithilfe einer intelligenten Skalierung.',
      'desc_face': 'Face Enhance glättet Hautunreinheiten und hebt Gesichtskonturen scharf hervor.',
      'desc_denoise': 'Denoise entfernt Bildrauschen bei schlechten Lichtverhältnissen für ein klares Bild.',
      'desc_unblur': 'Unblur reduziert Bewegungsunschärfe für gestochen scharfe Kanten.',
      'desc_colorize': 'Colorize B&W färbt alte Schwarz-Weiß-Aufnahmen mit lebensechten Farben ein.',
      'desc_restore': 'Old Photo Restore entfernt den gelblichen Alterungsschleier und bringt Kontraste zurück.',
      'desc_cartoon': 'Cartoon Effect verwandelt Fotos in einen gezeichneten Comic-Stil mit kräftigen Linien.',
      'desc_bg': 'Background Blur zeichnet den Hintergrund weich, um Motive wie bei einer DSLR freizustellen.',
      'desc_bg_cleanup': 'Background Cleanup ersetzt Hintergrund-Ablenkungen durch einen sauberen Studio-Hintergrund.',

      'feat_auto_title': 'Auto-Verbesserung',
      'feat_auto_sub': 'Korrigiert Farben, Kontrast & Schärfe',
      'feat_upscale_title': 'HD-Hochskalierung',
      'feat_upscale_sub': '2x / 4x ohne Unschärfe vergrößern',
      'feat_face_title': 'Gesichtsverbesserung',
      'feat_face_sub': 'Gesichter glätten & schärfen',
      'feat_denoise_title': 'Rauschen entfernen',
      'feat_denoise_sub': 'Körnung & Rauschen entfernen',
      'feat_unblur_title': 'Schärfen',
      'feat_unblur_sub': 'Bewegungsunschärfe reduzieren',
      'feat_colorize_title': 'Kolorieren S/W',
      'feat_colorize_sub': 'Farbe alten Fotos hinzufügen',
      'feat_restore_title': 'Alte Fotos restaurieren',
      'feat_restore_sub': 'Verblasst & Sepia reparieren',
      'feat_cartoon_title': 'Cartoon-Effekt',
      'feat_cartoon_sub': 'Künstlerische Kanten & Farben',
      'feat_bg_title': 'Hintergrund-Unschärfe',
      'feat_bg_sub': 'Hintergrund weich, Gesicht scharf',
      'feat_bg_cleanup_title': 'Hintergrund säubern',
      'feat_bg_cleanup_sub': 'Hintergrund-Ablenkungen entfernen',
    },
  };

  static String getText(String key, String langCode) {
    return localizedValues[langCode]?[key] ?? localizedValues['en']?[key] ?? key;
  }
}
