class AppStrings {
  static const String appName = 'PixelRevive';

  static const Map<String, Map<String, String>> localizedValues = {
    'en': {
      'tagline': 'Professional AI Photo Enhancer',
      'subTagline': 'Restore, Enhance & Unblur Your Old Memories Instantly',
      'chooseFeature': 'Select AI Feature',
      'onDevice': 'Instant on-device processing. No internet required.',
      'gallery': 'Gallery',
      'camera': 'Camera',
      'selectPhoto': 'Select a photo to begin',
      'importBlurry': 'Import a blurry or old photo to experience the AI filters',
      'changePhoto': 'Change Photo',
      'aiEditor': 'AI Editor',
      'enhance': 'Enhance',
      'compare': 'Compare',
      'save': 'Save',
      'share': 'Share',
      'unlockPremium': 'Unlock Premium Now',
      'premiumActive': '✓ Premium Active',
      'freeSaves': 'Free saves remaining today:',
      'proBenefitTitle': 'PRO Features Included',
      'tapToCompare': 'TAP TO COMPARE 👆',
      'benefit1': 'Ultra HD exports with no compression',
      'benefit2': 'No watermark on your finished photos',
      'benefit3': 'Unlimited daily photo enhancements',
      'benefit4': 'High-priority processing (Coming soon)',
      'benefit5': 'Batch processing for multiple photos',
      'onboardingTitle1': 'AI Old Photo Restore',
      'onboardingSub1': 'Instantly restore faded colors, remove aging sepia casts, and bring back deep contrasts to family archives.',
      'onboardingTitle2': 'Ultra HD 4K Upscale',
      'onboardingSub2': 'Enlarge your low-resolution, pixelated, or blurry images up to 4x with sharp edges and clear details.',
      'onboardingTitle3': 'DSLR Background Blur',
      'onboardingSub3': 'Simulate expensive camera bokeh. Focus on your subjects and smoothly blur complex background distractions.',
      
      // Feature Descriptions
      'desc_auto': 'One-Tap Auto Enhance automatically optimizes brightness, balances contrast, restores saturation, and sharpens soft details for a balanced photo.',
      'desc_upscale': 'HD Upscale lets you choose 2x or 4x enlargement. Premium users can use secure cloud upscaling when available; local fallback uses bicubic resizing plus sharpening.',
      'desc_face': 'Face Enhance optimizes portraits. It applies a smart local smoothing pass to reduce skin blemishes, followed by a local high-contrast details pass.',
      'desc_denoise': 'Denoise utilizes a bilateral noise-reduction filter. It sweeps away sensor grain and low-light artifacts while preserving structural edges.',
      'desc_unblur': 'Unblur deploys a high-pass unsharp masking algorithm, pulling back details in out-of-focus or motion-blurred shots.',
      'desc_colorize': 'Colorize B&W adds a warm color treatment to monochrome photos locally. Dedicated historical AI colorization can be added later through the backend model pipeline.',
      'desc_restore': 'Old Photo Restore improves faded, yellowed, or sepia photos by balancing color, contrast, noise, and sharpness. Cloud mode can enhance faces/details when available.',
      'desc_cartoon': 'Cartoon Effect processes the image with color quantization and edge tracing, turning normal photos into hand-drawn digital cel-shaded pop art.',
      'desc_bg': 'Background Blur simulates premium lens bokeh. It detects faces with on-device ML and keeps them sharp while smoothly softening the surrounding background.',
      'desc_bg_cleanup': 'BG Cleanup uses cloud remove-background when available. If cloud is unavailable, the local fallback reduces background distractions with center-focus cleanup.',

      // Result Screen
      'resultTitle': 'Before & After Swipe',
      'freeExports': 'Free exports remaining:',
      'watermarkNotice': 'Free saves include a small watermark on the corner.',
      'successTitle': 'Masterpiece Saved!',
      'successSub': 'Your enhanced photo has been saved to your phone gallery and kept in PixelRevive history.',
      'excellent': 'Excellent',
      'limitReachedTitle': 'Free Limit Reached',
      'limitReachedSub': 'You have utilized all free exports for today. Upgrade to Premium for unlimited exports without watermark and full HD resolution.',
      'later': 'Later',
      'goPremium': 'Go Premium',

      // Premium Screen
      'premiumTitle': 'Premium Upgrade',
      'devSettings': 'Developer API Settings',
      'enableCloud': 'Enable Cloud AI (Fal.ai)',
      'apiDesc': 'Insert your private Fal.ai API token to run state-of-the-art AI models (GFPGAN, Real-ESRGAN, CodeFormer) on high-speed cloud GPUs.',
      'apiHint': 'Paste Fal.ai Token here...',
      'selectPlan': 'Select a Plan',
      'weekly': 'Weekly',
      'yearly': 'Yearly Premium',
      'lifetime': 'Lifetime Ultra',
      'bestValue': 'BEST VALUE',
      'forever': 'FOREVER',
      'payOnce': 'Pay once, use forever',
      'autoRenews': 'Auto-renews easily. Cancel anytime.',
      'localUnlockSnack': 'Success! You are now a PRO member.',
      'billingNotice': 'Google Play Billing is wired and ready. After your Play Developer account is set up and products (premium_weekly / premium_yearly / premium_lifetime) are created, real purchases activate with no code change.',

      // Feature Card Titles & Subtitles
      'feat_auto_title': 'Auto Enhance',
      'feat_auto_sub': 'Fix colors, contrast & sharpness',
      'feat_upscale_title': 'HD Upscale',
      'feat_upscale_sub': '2x / 4x enlarge without blur',
      'feat_face_title': 'Face Enhance',
      'feat_face_sub': 'Sharpen & smooth faces',
      'feat_denoise_title': 'Denoise',
      'feat_denoise_sub': 'Remove grain & noise',
      'feat_unblur_title': 'Unblur',
      'feat_unblur_sub': 'Reduce motion & soft blur',
      'feat_colorize_title': 'Colorize B&W',
      'feat_colorize_sub': 'Add warm color to old photos',
      'feat_restore_title': 'Old Photo Restore',
      'feat_restore_sub': 'Fix faded, sepia & scratches',
      'feat_cartoon_title': 'Cartoon Effect',
      'feat_cartoon_sub': 'Artistic edge & color pop',
      'feat_bg_title': 'Background Blur',
      'feat_bg_sub': 'Blur background, keep face sharp',
      'feat_bg_cleanup_title': 'BG Cleanup',
      'feat_bg_cleanup_sub': 'Remove background distractions',
    },
    'es': {
      'tagline': 'Mejorador de Fotos AI Profesional',
      'subTagline': 'Restaure, mejore y aclare sus viejos recuerdos al instante',
      'chooseFeature': 'Seleccionar función de IA',
      'onDevice': 'Procesamiento instantáneo en el dispositivo. Sin internet.',
      'gallery': 'Galería',
      'camera': 'Cámara',
      'selectPhoto': 'Seleccione una foto para comenzar',
      'importBlurry': 'Importe una foto borrosa o vieja para experimentar la IA',
      'changePhoto': 'Cambiar Foto',
      'aiEditor': 'Editor de IA',
      'enhance': 'Mejorar',
      'compare': 'Comparar',
      'save': 'Guardar',
      'share': 'Compartir',
      'unlockPremium': 'Desbloquear Premium',
      'premiumActive': '✓ Premium Activo',
      'freeSaves': 'Guardados gratis restantes hoy:',
      'proBenefitTitle': 'Funciones PRO Incluidas',
      'benefit1': 'Exportaciones Ultra HD sin compresión',
      'benefit2': 'Sin marca de agua en tus fotos finales',
      'benefit3': 'Mejoras de fotos diarias ilimitadas',
      'benefit4': 'Procesamiento de alta prioridad (Muy pronto)',
      'benefit5': 'Procesamiento por lotes para varios elementos (Muy pronto)',
      'onboardingTitle1': 'Restauración de fotos antiguas por IA',
      'onboardingSub1': 'Restaura instantáneamente colores desvaídos, elimina tonos sepia y devuelve contrastes profundos.',
      'onboardingTitle2': 'Escalado Ultra HD 4K',
      'onboardingSub2': 'Amplía tus imágenes borrosas o pixeladas hasta 4 veces con bordes definidos y detalles claros.',
      'onboardingTitle3': 'Desenfoque de fondo DSLR',
      'onboardingSub3': 'Simula el bokeh de cámaras profesionales. Enfoca tus sujetos y desenfoca fondos complejos.',
      
      // Feature Descriptions
      'desc_auto': 'Auto Enhance optimiza automáticamente el brillo, equilibra el contraste, restaura la saturación y enfoca los detalles suaves.',
      'desc_upscale': 'HD Upscale escala su foto usando interpolación bicúbica para duplicar (2x) o cuadruplicar (4x) la resolución.',
      'desc_face': 'Face Enhance suaviza la piel reduciendo imperfecciones y resalta los rasgos clave de la cara como ojos y labios.',
      'desc_denoise': 'Denoise elimina el grano digital y el ruido de las fotos oscuras o con poca luz mientras mantiene los bordes nítidos.',
      'desc_unblur': 'Unblur reduce el movimiento de la cámara y el desenfoque suave recuperando detalles finos en la imagen.',
      'desc_colorize': 'Colorize B&W agrega tonos de piel realistas y colores naturales a las fotos antiguas en blanco y negro.',
      'desc_restore': 'Old Photo Restore elimina el tono amarillento y sepia del envejecimiento y recupera el contraste original.',
      'desc_cartoon': 'Cartoon Effect transforma tus fotos en un estilo artístico de dibujo animado con bordes oscuros y colores planos.',
      'desc_bg': 'Background Blur desenfoca el fondo de tus retratos imitando el efecto bokeh de lentes fotográficos profesionales.',
      'desc_bg_cleanup': 'BG Cleanup reemplaza los distracciones del fondo con un fondo de estudio limpio usando enmascaramiento inteligente centrado.',

      // Result Screen
      'resultTitle': 'Deslizar Antes y Después',
      'freeExports': 'Exportaciones gratuitas restantes:',
      'watermarkNotice': 'Los guardados gratuitos incluyen una marca de agua en la esquina.',
      'successTitle': '¡Obra Maestra Guardada!',
      'successSub': 'Su foto mejorada se ha guardado correctamente en la galería de su teléfono.',
      'excellent': 'Excelente',
      'limitReachedTitle': 'Límite de guardado alcanzado',
      'limitReachedSub': 'Has utilizado todas las exportaciones gratuitas para hoy. Actualiza a Premium para obtener descargas ilimitadas.',
      'later': 'Más tarde',
      'goPremium': 'Obtener Premium',

      // Premium Screen
      'premiumTitle': 'Mejora Premium',
      'devSettings': 'Configuración de API para Desarrolladores',
      'enableCloud': 'Habilitar Cloud AI (Fal.ai)',
      'apiDesc': 'Inserte su token de API de Fal.ai privado para ejecutar de manera instantánea modelos de IA de última generación (GFPGAN, Real-ESRGAN, CodeFormer) en servidores GPU en la nube.',
      'apiHint': 'Pegue el token de Fal.ai aquí...',
      'selectPlan': 'Seleccione un Plan',
      'weekly': 'Semanal',
      'yearly': 'Premium Anual',
      'lifetime': 'Ultra de por vida',
      'bestValue': 'BEST VALUE',
      'forever': 'PARA SIEMPRE',
      'payOnce': 'Paga una vez, usa para siempre',
      'autoRenews': 'Se renueva fácilmente. Cancela en cualquier momento.',
      'localUnlockSnack': '¡Éxito! Ahora eres miembro PRO.',
      'billingNotice': 'La facturación de Google Play está lista. Tras crear tu cuenta de desarrollador y los productos (premium_weekly / premium_yearly / premium_lifetime) en Play Console, las compras reales se activan sin cambios en el código.',

      // Feature Card Titles & Subtitles
      'feat_auto_title': 'Mejora Automática',
      'feat_auto_sub': 'Corrige colores, contraste y nitidez',
      'feat_upscale_title': 'Escalado HD',
      'feat_upscale_sub': 'Amplía 2x / 4x sin distorsión',
      'feat_face_title': 'Mejora de Rostro',
      'feat_face_sub': 'Suaviza y perfila facciones',
      'feat_denoise_title': 'Reducir Ruido',
      'feat_denoise_sub': 'Elimina grano y pixelación',
      'feat_unblur_title': 'Enfocar Foto',
      'feat_unblur_sub': 'Corrige el movimiento y borrosidad',
      'feat_colorize_title': 'Colorear B&N',
      'feat_colorize_sub': 'Añade color real a fotos viejas',
      'feat_restore_title': 'Restaurar Antigua',
      'feat_restore_sub': 'Quita manchas, sepia y dobleces',
      'feat_cartoon_title': 'Efecto Cartoon',
      'feat_cartoon_sub': 'Estilo cómic pop art de un toque',
      'feat_bg_title': 'Desenfocar Fondo',
      'feat_bg_sub': 'Efecto bokeh retrato profesional',
    },
    'fr': {
      'tagline': 'Améliorateur de Photos IA Professionnel',
      'subTagline': 'Restaurez, améliorez et défloutez vos vieux souvenirs instantanément',
      'chooseFeature': 'Sélectionner la fonction IA',
      'onDevice': 'Traitement instantané sur l\'appareil. Sans internet.',
      'gallery': 'Galerie',
      'camera': 'Appareil photo',
      'selectPhoto': 'Sélectionnez une photo pour commencer',
      'importBlurry': 'Importez une photo floue ou ancienne pour tester l\'IA',
      'changePhoto': 'Changer de photo',
      'aiEditor': 'Éditeur IA',
      'enhance': 'Améliorer',
      'compare': 'Comparer',
      'save': 'Enregistrer',
      'share': 'Partager',
      'unlockPremium': 'Débloquer Premium',
      'premiumActive': '✓ Premium Actif',
      'freeSaves': 'Sauvegardes gratuites restantes aujourd\'hui:',
      'proBenefitTitle': 'Fonctionnalités PRO Incluses',
      'benefit1': 'Exportations Ultra HD sans compression',
      'benefit2': 'Pas de filigrane sur vos photos finales',
      'benefit3': 'Améliorations quotidiennes illimitées',
      'benefit4': 'Traitement prioritaire (Prochainement)',
      'benefit5': 'Traitement par lots pour plusieurs éléments (Prochainement)',
      'onboardingTitle1': 'Restauration de Photos Anciennes par IA',
      'onboardingSub1': 'Restaurez instantanément les couleurs fanées, supprimez les teintes sépia et recréez des contrastes profonds.',
      'onboardingTitle2': 'Mise à l\'échelle Ultra HD 4K',
      'onboardingSub2': 'Agrandissez vos images floues ou pixelisées jusqu\'à 4x avec des contours nets.',
      'onboardingTitle3': 'Flou d\'arrière-plan DSLR',
      'onboardingSub3': 'Simulez le bokeh d\'un appareil photo professionnel. Restez focalisé sur vos sujets.',

      // Feature Descriptions
      'desc_auto': 'Auto Enhance ajuste automatiquement la luminosité, le contraste et la saturation pour un équilibre parfait.',
      'desc_upscale': 'HD Upscale double la résolution (2x) à l\'aide d\'un algorithme d\'interpolation bicubique de précision.',
      'desc_face': 'Face Enhance lisse la peau pour atténuer les imperfections tout en gardant les yeux et la bouche bien nets.',
      'desc_denoise': 'Denoise réduit le grain numérique et le bruit des clichés sombres sans lisser les détails structurels.',
      'desc_unblur': 'Unblur corrige le flou de bougé et de mise au point pour redonner de la netteté à vos clichés.',
      'desc_colorize': 'Colorize B&W ajoute des couleurs chaudes et naturelles sur vos anciennes photos monochromes.',
      'desc_restore': 'Old Photo Restore corrige la décoloration sepia du papier et restaure la clarté d\'origine des détails.',
      'desc_cartoon': 'Cartoon Effect applique un filtre de dessin animé stylisé avec des contours marqués et des aplats colorés.',
      'desc_bg': 'Background Blur floute l\'arrière-plan de vos portraits en simulant le flou artistique (bokeh) des objectifs DSLR.',
      'desc_bg_cleanup': 'Background Cleanup remplace les distractions de fond par un fond de studio propre en utilisant un masquage intelligent centré.',

      // Result Screen
      'resultTitle': 'Glisser Avant et Après',
      'freeExports': 'Exportations gratuites restantes:',
      'watermarkNotice': 'Les sauvegardes gratuites incluent un léger filigrane dans le coin.',
      'successTitle': 'Chef-d\'œuvre Enregistré !',
      'successSub': 'Votre photo améliorée se trouve dans votre galerie.',
      'excellent': 'Excellent',
      'limitReachedTitle': 'Limite gratuite atteinte',
      'limitReachedSub': 'Vous avez atteint la limite gratuite.',
      'later': 'Plus tard',
      'goPremium': 'Passer Premium',

      // Premium Screen
      'premiumTitle': 'Mise à niveau Premium',
      'devSettings': 'Paramètres de l\'API développeur',
      'enableCloud': 'Activer Cloud AI (Fal.ai)',
      'apiDesc': 'Insérez votre jeton privé de l\'API Fal.ai pour exécuter des modèles d\'IA haut de gamme (GFPGAN, Real-ESRGAN, CodeFormer) sur des serveurs GPU cloud ultra-rapides.',
      'apiHint': 'Collez le jeton Fal.ai ici...',
      'selectPlan': 'Sélectionnez un plan',
      'weekly': 'Hebdomadaire',
      'yearly': 'Premium Annuel',
      'lifetime': 'Ultra à vie',
      'bestValue': 'MEILLEURE VALEUR',
      'forever': 'POUR TOUJOURS',
      'payOnce': 'Payez une fois, utilisez pour toujours',
      'autoRenews': 'Renouvellement facile. Annulez à tout moment.',
      'localUnlockSnack': 'Succès ! Vous êtes maintenant membre PRO.',
      'billingNotice': 'La facturation Google Play est prête. Après avoir créé les produits (premium_weekly / premium_yearly / premium_lifetime) dans la Play Console, les achats réels s\'activent sans modification de code.',
    },
    'ur': {
      'tagline': 'AI فوٹو اینہانسر',
      'subTagline': 'اپنی پرانی اور دھندلی تصاویر کو سیکنڈوں میں ٹھیک کریں',
      'chooseFeature': 'ٹول منتخب کریں',
      'onDevice': 'پروسیسنگ آپ کے فون پر ہوتی ہے، کسی انٹرنیٹ کی ضرورت نہیں۔',
      'gallery': 'گیلری',
      'camera': 'کیمرہ',
      'selectPhoto': 'شروع کرنے کے لیے ایک تصویر منتخب کریں',
      'importBlurry': 'تصویر منتخب کر کے جادو دیکھیں',
      'changePhoto': 'تصویر تبدیل کریں',
      'aiEditor': 'AI ایڈیٹر',
      'enhance': 'بہتر بنائیں',
      'compare': 'موازنہ کریں',
      'save': 'محفوظ کریں',
      'share': 'شیر کریں',
      'unlockPremium': 'پریمیم حاصل کریں',
      'premiumActive': '✓ پریمیم فعال ہے',
      'freeSaves': 'آج کے مفت بچاؤ باقی ہیں:',
      'proBenefitTitle': 'پرو خصوصیات شامل ہیں',
      'tapToCompare': 'موازنہ کے لیے دبائیں 👆',
      'benefit1': 'بغیر کسی کمپریشن کے الٹرا ایچ ڈی ایکسپورٹ',
      'benefit2': 'آپ کی آخری تصاویر پر کوئی واٹر مارک نہیں ہے',
      'benefit3': 'لامحدود روزانہ تصویر میں بہتری',
      'benefit4': 'اعلیٰ ترجیحی پروسیسنگ (بہت جلد)',
      'benefit5': 'ایک ساتھ متعدد تصاویر کی پروسیسنگ (بہت جلد)',
      'onboardingTitle1': 'AI پرانی تصویر کی بحالی',
      'onboardingSub1': 'فوری طور پر مدھم رنگوں کو بحال کریں، پرانی پیلی رنگت کو ختم کریں، اور گہرے رنگوں کو واپس لائیں۔',
      'onboardingTitle2': 'الٹرا ایچ ڈی 4K اپ اسکیل',
      'onboardingSub2': 'دھندلی تصویر کو 4K ریزولوشن میں تبدیل کریں۔',
      'onboardingTitle3': 'DSLR بیک گراؤنڈ بلر',
      'onboardingSub3': 'پس منظر کو دھندلا کر کے چہرے کو نمایاں کریں۔',

      'desc_auto': 'موبائل پر روشنی اور رنگوں کو آٹو ایڈجسٹ کریں۔',
      'desc_upscale': 'تصویر کی ریزولیوشن کو 2x یا 4x تک بڑھائیں۔',
      'desc_face': 'چہرے کی جھریاں دور کر کے ملامح کو واضح کریں۔',
      'desc_denoise': 'اندھیرے والی تصاویر کا دانہ دار پن دور کریں۔',
      'desc_unblur': 'تصویر کا دھندلا پن دور کریں۔',
      'desc_colorize': 'پرانی تصاویر کو رنگین بنائیں۔',
      'desc_restore': 'پرانی تصویروں کو بحال کریں۔',
      'desc_cartoon': 'تصویر کو کارٹون آرٹ بنائیں۔',
      'desc_bg': 'بیک گراؤنڈ بلر کریں۔',
      'desc_bg_cleanup': 'بیک گراؤنڈ کلین اپ پس منظر کو اسٹوڈیو بیک گراؤنڈ سے تبدیل کرتی ہے۔',

      // Result Screen
      'resultTitle': 'موازنہ سوائپ کریں',
      'freeExports': 'مفت برآمدات باقی ہیں:',
      'watermarkNotice': 'مفت بچتوں میں کونے پر ایک چھوٹا واٹر مارک شامل ہے۔',
      'successTitle': 'شہ پارہ محفوظ ہو گیا!',
      'successSub': 'تصویر آپ کے فون کی گیلری میں محفوظ کر دی گئی ہے۔',
      'excellent': 'بہترین',
      'limitReachedTitle': 'مفت حد ختم ہو گئی',
      'limitReachedSub': 'آج کی مفت بچتیں ختم ہو گئیں۔',
      'later': 'بعد میں',
      'goPremium': 'پریمیم حاصل کریں',

      // Premium Screen
      'premiumTitle': 'پریمیم اپ گریڈ',
      'devSettings': 'ڈیولپر API سیٹنگز',
      'enableCloud': 'کلاؤڈ AI فعال کریں (Fal.ai)',
      'apiDesc': 'ہائی اسپیڈ کلاؤڈ سرورز پر بہترین ماڈلز (GFPGAN، Real-ESRGAN) چلانے کے لیے اپنا ذاتی Fal.ai ٹوکن درج کریں۔',
      'apiHint': 'یہاں Fal.ai ٹوکن پیسٹ کریں...',
      'selectPlan': 'ایک پلان منتخب کریں',
      'weekly': 'ہفتہ وار',
      'yearly': 'سالانہ پریمیم',
      'lifetime': 'لائف ٹائم الٹرا',
      'bestValue': 'بہترین قیمت',
      'forever': 'ہمیشہ کے لیے',
      'payOnce': 'ایک بار ادا کریں، ہمیشہ استعمال کریں',
      'autoRenews': 'آسانی سے تجدید ہوتی ہے۔ کبھی بھی منسوخ کریں۔',
      'localUnlockSnack': 'کامیابی! آپ اب PRO ممبر ہیں۔',
      'billingNotice': 'گوگل پلے بلنگ تیار ہے۔ پلے کنسول میں پراڈکٹس (premium_weekly / premium_yearly / premium_lifetime) بنانے کے بعد، اصلی خریداری کوڈ میں کوئی تبدیلی کیے بغیر فعال ہو جائے گی۔',
    },
    'ar': {
      'tagline': 'محسن صور احترافي بالذكاء الاصطناعي',
      'subTagline': 'استرجع ذكرياتك القديمة وقم بتحسينها وإزالة التشويش فورًا',
      'chooseFeature': 'اختر ميزة الذكاء الاصطناعي',
      'onDevice': 'معالجة فورية على الجهاز. لا يلزم الاتصال بالإنترنت.',
      'gallery': 'المعرض',
      'camera': 'الكاميرا',
      'selectPhoto': 'حدد صورة للبدء',
      'importBlurry': 'قم باستيراد صورة قديمة أو ضبابية لتجربة فلاتر الذكاء الاصطناعي',
      'changePhoto': 'تغيير الصورة',
      'aiEditor': 'محرر الذكاء الاصطناعي',
      'enhance': 'تحسين',
      'compare': 'مقارنة',
      'save': 'حفظ',
      'share': 'مشاركة',
      'unlockPremium': 'فتح العضوية المميزة',
      'premiumActive': '✓ العضوية المميزة نشطة',
      'freeSaves': 'المرات المجانية المتبقية للحفظ اليوم:',
      'proBenefitTitle': 'الميزات الاحترافية المضمنة',
      'tapToCompare': 'انقر للمقارنة 👆',
      'benefit1': 'تصدير بجودة Ultra HD بدون أي ضغط',
      'benefit2': 'لا توجد علامة مائية على صورك النهائية',
      'benefit3': 'تحسينات صور يومية غير محدودة',
      'benefit4': 'معالجة ذات أولوية عالية (قريبًا)',
      'benefit5': 'معالجة الدفعات لعدة عناصر (قريبًا)',
      'onboardingTitle1': 'استعادة الصور القديمة بالذكاء الاصطناعي',
      'onboardingSub1': 'استرجع الألوان الباهتة فورًا، وأزل درجات اللون البني القديمة، واستعد التباين العميق.',
      'onboardingTitle2': 'ترقية الجودة إلى Ultra HD 4K',
      'onboardingSub2': 'قم بتكبير صورك منخفضة الدقة أو الضبابية حتى 4 مرات بحواف حادة وتفاصيل واضحة.',
      'onboardingTitle3': 'تمويه الخلفية الاحترافي',
      'onboardingSub3': 'قم بمحاكاة بوكيه الكاميرات الاحترافية. ركز على العناصر وقم بتمويه الخلفيات المشتتة.',

      // Feature Descriptions
      'desc_auto': 'تقوم ميزة Auto Enhance بضبط السطوع والتباين تلقائيًا وإبراز الألوان الباهتة.',
      'desc_upscale': 'تضاعف ميزة HD Upscale دقة الصورة مرتين (2x) أو أربعة أضعاف (4x) باستخدام خوارزمية تكبير ذكية.',
      'desc_face': 'Face Enhance تنعم البشرة وإزالة الشوائب وتوضح تفاصيل العينين والشفتين بدقة.',
      'desc_denoise': 'تزيل ميزة Denoise الحبيبات الرقمية والتشويش من الصور الليلية مع الحفاظ على وضوح التفاصيل.',
      'desc_unblur': 'تعالج ميزة Unblur ضبابية الحركة والاهتزاز لاستعادة وضوح الصور الملتشطة.',
      'desc_colorize': 'تضيف ميزة Colorize B&W ألوانًا دافئة وواقعية على صورك القديمة أحادية اللون.',
      'desc_restore': 'تزيل ميزة Old Photo Restore اصفرار الورق ودرجات السيبيا القديمة وتعيد التباين الغني.',
      'desc_cartoon': 'تحول ميزة Cartoon Effect صورك الشخصية إلى لوحة كرتونية فنية بخطوط واضحة وألوان زاهية.',
      'desc_bg': 'تقوم ميزة Background Blur بتمويه خلفية صورك الشخصية لتبدو وكأنها ملتقطة بعدسة كاميرا احترافية.',
      'desc_bg_cleanup': 'Background Cleanup تستبدل مشتتات الخلفية بخلفية استوديو نظيفة باستخدام قناع ذكي مركزي.',

      // Result Screen
      'resultTitle': 'مقارنة بالسحب قبل وبعد',
      'freeExports': 'مرات التصدير المجانية المتبقية:',
      'watermarkNotice': 'الحفظ المجاني يتضمن علامة مائية صغيرة في الزاوية.',
      'successTitle': 'تم حفظ التحفة الفنية!',
      'successSub': 'تم حفظ صورتك المحسنة بنجاح في مجلد معرض الصور الأصلي بهاتفك.',
      'excellent': 'ممتاز',
      'limitReachedTitle': 'تم الوصول إلى الحد الأقصى',
      'limitReachedSub': 'لقد استهلكت جميع المرات المجانية لليوم. قم بترقية العضوية لتنزيلات غير محدودة وبدون علامة مائية.',
      'later': 'لاحقًا',
      'goPremium': 'الذهاب للمميز',

      // Premium Screen
      'premiumTitle': 'الترقية المميزة',
      'devSettings': 'إعدادات المطور الخاصة بـ API',
      'enableCloud': 'تفعيل كود الذكاء الاصطناعي (Fal.ai)',
      'apiDesc': 'أدخل رمز API الخاص بك لـ Fal.ai لتشغيل أقوى النماذج (GFPGAN, Real-ESRGAN) على خوادم سحابية فائقة السرعة.',
      'apiHint': 'ألصق رمز Fal.ai هنا...',
      'selectPlan': 'اختر خطة الاشتراك',
      'weekly': 'أسبوعي',
      'yearly': 'مميز سنوي',
      'lifetime': 'عضوية مدى الحياة',
      'bestValue': 'أفضل قيمة',
      'forever': 'للأبد',
      'payOnce': 'ادفع مرة واحدة، واستخدم للأبد',
      'autoRenews': 'يتجدد بسهولة. ألغِ في أي وقت.',
      'localUnlockSnack': 'نجاح! أنت الآن عضو PRO.',
      'billingNotice': 'نظام الدفع عبر Google Play جاهز. بعد إنشاء المنتجات (premium_weekly / premium_yearly / premium_lifetime) في Play Console، تُفعَّل عمليات الشراء الحقيقية دون أي تغيير في الكود.',
    },
    'de': {
      'tagline': 'Professioneller KI-Foto-Verbesserer',
      'subTagline': 'Stellen Sie alte Erinnerungen sofort wieder her, verbessern und schärfen Sie sie',
      'chooseFeature': 'KI-Funktion wählen',
      'onDevice': 'Sofortige Offline-Verarbeitung. Kein Internet erforderlich.',
      'gallery': 'Galerie',
      'camera': 'Kamera',
      'selectPhoto': 'Wählen Sie ein Foto aus',
      'importBlurry': 'Importieren Sie ein unscharfes Foto, um KI-Filter zu testen',
      'changePhoto': 'Foto ändern',
      'aiEditor': 'KI-Editor',
      'enhance': 'Verbessern',
      'compare': 'Vergleichen',
      'save': 'Speichern',
      'share': 'Teilen',
      'unlockPremium': 'Premium freischalten',
      'premiumActive': '✓ Premium Aktiv',
      'freeSaves': 'Verbleibende freie Speicherungen heute:',
      'proBenefitTitle': 'PRO-Funktionen Enthalten',
      'tapToCompare': 'ZUM VERGLEICHEN TIPPEN 👆',
      'benefit1': 'Ultra HD-Exporte ohne Komprimierung',
      'benefit2': 'Kein Wasserzeichen auf Ihren fertigen Fotos',
      'benefit3': 'Unbegrenzte tägliche Foto-Verbesserungen',
      'benefit4': 'Prioritäre Verarbeitung (In Kürze)',
      'benefit5': 'Stapelverarbeitung für mehrere Bilder (In Kürze)',
      'onboardingTitle1': 'KI-Fotowiederherstellung',
      'onboardingSub1': 'Stellen Sie verblasste Farben sofort wieder her und bringen Sie tiefe Kontraste zurück.',
      'onboardingTitle2': 'Ultra HD 4K Skalierung',
      'onboardingSub2': 'Vergrößern Sie unscharfe oder pixelige Bilder um das bis zu 4-Fache mit klaren Kanten.',
      'onboardingTitle3': 'DSLR Background-Weichzeichnung',
      'onboardingSub3': 'Simulieren Sie professionelles Kamera-Bokeh. Fokussieren Sie Ihre Motive.',

      // Feature Descriptions
      'desc_auto': 'Auto Enhance optimiert Helligkeit, Kontrast und Sättigung für ein perfekt ausgewogenes Foto.',
      'desc_upscale': 'HD Upscale verdoppelt (2x) oder vervierfacht (4x) die Auflösung Ihres Fotos mithilfe einer intelligenten Skalierungsalgorithmen.',
      'desc_face': 'Face Enhance glättet Hautunreinheiten sanft und hebt Gesichtskonturen (Augen, Lippen) scharf hervor.',
      'desc_denoise': 'Denoise entfernt Bildrauschen und Körnung bei schlechten Lichtverhältnissen für ein klares Bild.',
      'desc_unblur': 'Unblur reduziert Bewegungsunschärfe und Schärfungsfehler für gestochen scharfe Kanten.',
      'desc_colorize': 'Colorize B&W färbt alte Schwarz-Weiß-Aufnahmen mit lebensechten, warmen Farben ein.',
      'desc_restore': 'Old Photo Restore entfernt den gelblichen Alterungsschleier und bringt Kontraste zurück.',
      'desc_cartoon': 'Cartoon Effect verwandelt Fotos in einen gezeichneten Comic-Stil mit kräftigen Linien.',
      'desc_bg': 'Background Blur zeichnet den Hintergrund weich, um Ihre Motive wie bei einer DSLR-Kamera freizustellen.',
      'desc_bg_cleanup': 'Background Cleanup ersetzt Hintergrund-Ablenkungen durch einen sauberen Studio-Hintergrund mit intelligentem Zentrumsmaskierung.',

      // Result Screen
      'resultTitle': 'Vorher & Nachher wischen',
      'freeExports': 'Verbleibende freie Exporte:',
      'watermarkNotice': 'Kostenlose Speicherungen enthalten ein kleines Wasserzeichen in der Ecke.',
      'successTitle': 'Meisterwerk gespeichert!',
      'successSub': 'Ihr verbessertes Foto wurde erfolgreich im Galerieordner Ihres Telefons gespeichert.',
      'excellent': 'Ausgezeichnet',
      'limitReachedTitle': 'Kostenloses Limit erreicht',
      'limitReachedSub': 'Sie haben heute alle kostenlosen Speicherkontingente aufgebraucht. Upgraden Sie auf Premium für unbegrenzte Exporte.',
      'later': 'Später',
      'goPremium': 'Zu Premium wechseln',

      // Premium Screen
      'premiumTitle': 'Premium-Upgrade',
      'devSettings': 'Entwickler-API-Einstellungen',
      'enableCloud': 'Cloud-KI aktivieren (Fal.ai)',
      'apiDesc': 'Fügen Sie Ihren privaten Fal.ai-API-Token ein, um erstklassige KI-Modelle (GFPGAN, Real-ESRGAN, CodeFormer) auf schnellen Cloud-Servern auszuführen.',
      'apiHint': 'Fal.ai-Token hier einfügen...',
      'selectPlan': 'Wählen Sie einen Plan',
      'weekly': 'Wöchentlich',
      'yearly': 'Jährliches Premium',
      'lifetime': 'Lebenslanges Ultra',
      'bestValue': 'BESTER WERT',
      'forever': 'FÜR IMMER',
      'payOnce': 'Einmal zahlen, für immer nutzen',
      'autoRenews': 'Einfache Verlängerung. Jederzeit kündbar.',
      'localUnlockSnack': 'Erfolg! Du bist jetzt PRO-Mitglied.',
      'billingNotice': 'Die Google Play-Abrechnung ist eingerichtet. Nach dem Erstellen der Produkte (premium_weekly / premium_yearly / premium_lifetime) in der Play Console werden echte Käufe ohne Codeänderung aktiviert.',
    }
  };

  static String getText(String key, String langCode) {
    return localizedValues[langCode]?[key] ?? localizedValues['en']?[key] ?? key;
  }
}