class AppStrings {
  static const String appName = 'PixelRevive';

  static const Map<String, Map<String, String>> localizedValues = {
    'en': {
      'tagline': 'Professional AI Photo Enhancer',
      'subTagline': 'Restore, Enhance & Unblur Your Old Memories Instantly',
      'chooseFeature': 'Select AI Feature',
      'onDevice': 'Instant on-device processing. No internet required.',
      'gallery': 'Gallery',
      'camera': 'Camera',
      'selectPhoto': 'Select a photo to begin',
      'importBlurry': 'Import a blurry or old photo to experience the AI filters',
      'changePhoto': 'Change Photo',
      'aiEditor': 'AI Editor',
      'enhance': 'Enhance',
      'compare': 'Compare',
      'save': 'Save',
      'share': 'Share',
      'unlockPremium': 'Unlock Premium Now',
      'premiumActive': '✓ Premium Active',
      'freeSaves': 'Free saves remaining today:',
      'proBenefitTitle': 'PRO Features Included',
      'tapToCompare': 'TAP TO COMPARE 👆',
      'benefit1': 'Ultra HD exports with no compression',
      'benefit2': 'No watermark on your finished photos',
      'benefit3': 'Unlimited daily photo enhancements',
      'benefit4': 'High-priority processing (Coming soon)',
      'benefit5': 'Batch processing for multiple items (Coming soon)',
      'onboardingTitle1': 'AI Old Photo Restore',
      'onboardingSub1': 'Instantly restore faded colors, remove aging sepia casts, and bring back deep contrasts to family archives.',
      'onboardingTitle2': 'Ultra HD 4K Upscale',
      'onboardingSub2': 'Enlarge your low-resolution, pixelated, or blurry images up to 4x with sharp edges and clear details.',
      'onboardingTitle3': 'DSLR Background Blur',
      'onboardingSub3': 'Simulate expensive camera bokeh. Focus on your subjects and smoothly blur complex background distractions.',
      
      // Feature Descriptions
      'desc_auto': 'One-Tap Auto Enhance automatically optimizes brightness, balances contrast, restores saturation, and sharpens soft details for a balanced photo.',
      'desc_upscale': 'HD Upscale uses a bicubic interpolation scaling algorithm to double (2x) the resolution of your photo while sharpening edges to reduce blur.',
      'desc_face': 'Face Enhance optimizes portraits. It applies a smart local smoothing pass to reduce skin blemishes, followed by a local high-contrast details pass.',
      'desc_denoise': 'Denoise utilizes a bilateral noise-reduction filter. It sweeps away sensor grain and low-light artifacts while preserving structural edges.',
      'desc_unblur': 'Unblur deploys a high-pass unsharp masking algorithm, pulling back details in out-of-focus or motion-blurred shots.',
      'desc_colorize': 'Colorize B&W reads black & white luminance layers and maps warm, realistic organic skin tones and ambient values back onto old monochrome photos.',
      'desc_restore': 'Old Photo Restore targets antique sepia or yellowed paper. It neutralizes aging shifts, optimizes faded dynamic range, and clarifies old pixels.',
      'desc_cartoon': 'Cartoon Effect processes the image with color quantization and edge tracing, turning normal photos into hand-drawn digital cel-shaded pop art.',
      'desc_bg': 'Background Blur simulates premium lens bokeh. It centers focus around the central photographic subject and gently softens the background.',
      'desc_bg_cleanup': 'Background Cleanup erases background clutter or replaces the background entirely with a clean solid color using advanced AI segmentation.',

      // Result Screen
      'resultTitle': 'Before & After Swipe',
      'freeExports': 'Free exports remaining:',
      'watermarkNotice': 'Free saves include a small watermark on the corner.',
      'successTitle': 'Masterpiece Saved!',
      'successSub': 'Your beautifully enhanced photo has been successfully saved to your phone\'s native gallery folder.',
      'excellent': 'Excellent',
      'limitReachedTitle': 'Free Limit Reached',
      'limitReachedSub': 'You have utilized all free exports for today. Upgrade to Premium for unlimited exports without watermark and full HD resolution.',
      'later': 'Later',
      'goPremium': 'Go Premium',

      // Premium Screen
      'premiumTitle': 'Premium Upgrade',
      'devSettings': 'Developer API Settings',
      'enableCloud': 'Enable Cloud AI (Replicate)',
      'apiDesc': 'Insert your private Replicate API token to run state-of-the-art AI models (GFPGAN, Real-ESRGAN, CodeFormer) on high-speed cloud GPUs.',
      'apiHint': 'Paste Replicate Token here...',
      'selectPlan': 'Select a Plan',
      'weekly': 'Weekly',
      'yearly': 'Yearly Premium',
      'lifetime': 'Lifetime Ultra',
      'bestValue': 'BEST VALUE',
      'forever': 'FOREVER',
      'payOnce': 'Pay once, use forever',
      'autoRenews': 'Auto-renews easily. Cancel anytime.',
      'localUnlockSnack': 'Success! You are now a PRO member.',
      'billingNotice': 'Real Google Play / Apple App Store Billing will be connected in next step. Clicking the unlock button simulates billing completion locally for sandbox testing.',

      // Feature Card Titles & Subtitles
      'feat_auto_title': 'Auto Enhance',
      'feat_auto_sub': 'Fix colors, contrast & sharpness',
      'feat_upscale_title': 'HD Upscale',
      'feat_upscale_sub': '2x / 4x enlarge without blur',
      'feat_face_title': 'Face Enhance',
      'feat_face_sub': 'Sharpen & smooth faces',
      'feat_denoise_title': 'Denoise',
      'feat_denoise_sub': 'Remove grain & noise',
      'feat_unblur_title': 'Unblur',
      'feat_unblur_sub': 'Reduce motion & soft blur',
      'feat_colorize_title': 'Colorize B&W',
      'feat_colorize_sub': 'Add warm color to old photos',
      'feat_restore_title': 'Old Photo Restore',
      'feat_restore_sub': 'Fix faded, sepia & scratches',
      'feat_cartoon_title': 'Cartoon Effect',
      'feat_cartoon_sub': 'Artistic edge & color pop',
      'feat_bg_title': 'Background Blur',
      'feat_bg_sub': 'Blur background, keep face sharp',
      'feat_bg_cleanup_title': 'BG Cleanup',
      'feat_bg_cleanup_sub': 'Remove background distractions',
    }
  };

  static String getText(String key, String langCode) {
    return localizedValues[langCode]?[key] ?? localizedValues['en']?[key] ?? key;
  }
}